local colors = require("colors")

local data = {}

-- ═══════════════════════════════════════════════════════════════════════════
-- RECORDS
-- ═══════════════════════════════════════════════════════════════════════════

data.records = {

    ["INC-2047"] = {
        type = "incident",
        title = "ANOMALOUS WATER CONSUMPTION - SECTOR 9",
        classification = "PRIORITY-2",
        date = "2071-03-14",
        filed_by = "AUTOMATED MONITORING SYSTEM",
        sector = "6",
        content = {
            "Automated flow monitoring has detected sustained water consumption on",
            "distribution line S9-A, which services Sector 9. Sector 9 has been",
            "under containment seal since Directive DIR-7701 was enacted on",
            "2065-08-22 following Incident INC-2031 (biological contamination).",
            "",
            "Expected flow on line S9-A:  0.0 L/day",
            "Measured flow on line S9-A:  847.3 L/day (30-day rolling average)",
            "",
            "Discrepancy has been present for an estimated 1,460+ days based on",
            "historical flow data reconstruction. Previous readings fell within",
            "tolerance bands due to allowable system pressure fluctuation margins.",
            "",
            "Current aquifer depletion rates have narrowed tolerance bands, causing",
            "this anomaly to exceed automated detection thresholds for the first time.",
            "",
            "RECOMMENDATION: Immediate investigation required. Possible causes:",
            "  - Valve seal degradation permitting passive flow",
            "  - Sensor calibration error",
            "  - Unauthorized modification to distribution infrastructure",
            "",
            "Cross-reference: MLOG-WTR-1201, INC-2031, DIR-7701",
        },
        keywords = {"water", "sector 9", "anomaly", "consumption", "s9-a", "flow", "pressure", "aquifer"},
        access_level = 1,
        related = {"INC-2031", "MLOG-WTR-1201", "DIR-7701"},
    },

    ["INC-2031"] = {
        type = "incident",
        title = "BIOLOGICAL CONTAMINATION EVENT - SECTOR 9",
        classification = "PRIORITY-1 [RESOLVED]",
        date = "2065-08-20",
        filed_by = "DR. MARCUS CHEN, MEDICAL DIVISION",
        sector = "9",
        content = {
            "On 2065-08-18, routine air quality sampling in Sector 9 Residential",
            "Block C returned anomalous biological markers consistent with possible",
            "pathogenic activity. Subsequent sampling confirmed presence of unidentified",
            "organic compounds in ventilation substrate.",
            "",
            "Medical assessment determined contamination posed unacceptable risk to",
            "silo population. Containment protocol was initiated under DIR-7701.",
            "",
            "Sector 9 was sealed at 0347 hours on 2065-08-22.",
            "",
            "Population count at time of seal: 0 (evacuation completed 2065-08-21)",
            "Reported casualties: 0",
            "",
            "NOTE: All personnel were relocated to emergency housing in Sectors 2-3.",
            "Full decontamination timeline has not been established.",
            "",
            "Medical signoff: Dr. Marcus Chen, CIV-0088",
            "Authorization: Director E. Hale, CIV-0003",
            "",
            "Cross-reference: DIR-7701, WIT-088-A, MLOG-S9-0847",
        },
        keywords = {"contamination", "sector 9", "biological", "seal", "pathogen", "chen", "hale", "evacuation"},
        access_level = 1,
        related = {"DIR-7701", "WIT-088-A", "MLOG-S9-0847", "CIV-0088", "CIV-0003"},
    },

    ["INC-2019"] = {
        type = "incident",
        title = "UNAUTHORIZED ACCESS - WATER SUBSYSTEM JUNCTION WTR-J7",
        classification = "PRIORITY-3 [RESOLVED]",
        date = "2067-04-11",
        filed_by = "SECURITY DIVISION",
        sector = "6",
        content = {
            "Security sensors logged unauthorized badge access at water subsystem",
            "junction WTR-J7 at 0214 hours. Junction WTR-J7 services distribution",
            "lines for Sectors 6, 9, and 12.",
            "",
            "Badge identified: CIV-0112 (Elena Vasik, Maintenance Technician III).",
            "",
            "Subject stated she was responding to a pressure alarm that was not",
            "logged in the central monitoring system. Inspection of junction showed",
            "no irregularities. Subject was issued a verbal warning.",
            "",
            "Supervisor note: CIV-0112 has Level 3 maintenance clearance. Access",
            "to WTR-J7 is technically within scope but outside scheduled hours.",
            "No further action recommended.",
            "",
            "Cross-reference: CIV-0112",
        },
        keywords = {"unauthorized", "access", "water", "vasik", "elena", "junction", "wtr-j7", "badge"},
        access_level = 1,
        related = {"CIV-0112"},
    },

    ["INC-1987"] = {
        type = "incident",
        title = "POPULATION CENSUS RECONCILIATION FAILURE",
        classification = "PRIORITY-4 [ARCHIVED]",
        date = "2066-01-15",
        filed_by = "RECORDS DIVISION",
        sector = "1",
        content = {
            "Annual population census for fiscal year 2065 produced a reconciliation",
            "discrepancy of -43 individuals between sector-level head counts and",
            "central registry totals.",
            "",
            "Breakdown by sector:",
            "  Sector 1:   142  (expected: 142)   [MATCH]",
            "  Sector 2:   386  (expected: 386)   [MATCH]",
            "  Sector 3:   714  (expected: 714)   [MATCH]",
            "  Sector 4:   203  (expected: 203)   [MATCH]",
            "  Sector 5:   298  (expected: 298)   [MATCH]",
            "  Sector 6:    89  (expected:  89)   [MATCH]",
            "  Sector 7:    67  (expected:  67)   [MATCH]",
            "  Sector 8:   112  (expected: 112)   [MATCH]",
            "  Sector 9:     0  (expected:   0)   [MATCH]  *SEALED*",
            "  Sector 10:   41  (expected:  41)   [MATCH]",
            "  Sector 11:   33  (expected:  33)   [MATCH]",
            "  Sector 12:   56  (expected:  56)   [MATCH]",
            "",
            "  TOTAL:    2,141  (expected: 2,141)",
            "  REGISTRY: 2,184",
            "  DISCREPANCY: -43",
            "",
            "Records division notes: Discrepancy attributed to delayed processing",
            "of casualty reports from Sector 9 contamination event (INC-2031).",
            "Registry entries for 43 individuals updated to DECEASED status.",
            "",
            "Filed by: Kira Okafor, CIV-0201",
            "NOTE FROM CLERK: Casualty reports for these 43 individuals were not",
            "filed through standard medical channels. Processed per administrative",
            "directive. See DIR-9901.",
            "",
            "Cross-reference: INC-2031, DIR-9901, CIV-0201",
        },
        keywords = {"population", "census", "discrepancy", "43", "deceased", "registry", "okafor", "dir-9901", "casualty"},
        access_level = 1,
        related = {"INC-2031", "DIR-9901", "CIV-0201"},
    },

    ["INC-2044"] = {
        type = "incident",
        title = "QUARTERLY RESOURCE PROJECTION - WATER DEFICIT",
        classification = "PRIORITY-2",
        date = "2071-02-28",
        filed_by = "RESOURCE ALLOCATION DIVISION",
        sector = "1",
        content = {
            "Quarterly projection for Q2 2071 indicates water reserves will fall",
            "below critical threshold within 180 days at current consumption rates.",
            "",
            "Current aquifer output:    12,400 L/day",
            "Current total consumption: 11,870 L/day",
            "Reserve buffer:                530 L/day (4.3%)",
            "",
            "Minimum safe buffer per DIR-7702: 8.0% (992 L/day)",
            "",
            "Contributing factors:",
            "  - Aquifer output declining 0.3% per quarter (geological trend)",
            "  - Population growth rate 0.4% annually",
            "  - Agricultural demand increased 2.1% (crop cycle expansion)",
            "  - Unaccounted system losses averaging 847 L/day",
            "",
            "RECOMMENDATION: Immediate audit of all distribution lines. Consider",
            "ration reduction per DIR-7702 protocols.",
            "",
            "Cross-reference: DIR-7702, INC-2047",
        },
        keywords = {"water", "deficit", "resource", "aquifer", "ration", "consumption", "shortage", "reserve", "847"},
        access_level = 1,
        related = {"DIR-7702", "INC-2047"},
    },

    ["INC-2033"] = {
        type = "incident",
        title = "SECTOR 9 POST-SEAL INSPECTION REPORT",
        classification = "PRIORITY-3 [ARCHIVED]",
        date = "2065-11-03",
        filed_by = "MAINTENANCE DIVISION",
        sector = "9",
        content = {
            "Post-seal inspection of Sector 9 conducted via remote monitoring",
            "systems and external access points.",
            "",
            "Infrastructure status:",
            "  - Structural integrity: NOMINAL",
            "  - Air filtration: OFFLINE (as expected per seal protocol)",
            "  - Water distribution: NOMINAL (passive pressure maintained)",
            "  - Power grid: REDUCED (emergency lighting only)",
            "  - Communications: DISABLED",
            "",
            "Biological monitoring:",
            "  - Air samples at seal boundary: CLEAR",
            "  - No pathogenic markers detected in adjacent sectors",
            "  - Contamination appears contained within Sector 9",
            "",
            "OBSERVATION: Remote thermal imaging detected intermittent heat",
            "signatures in Residential Block C. Attributed to residual equipment",
            "operation and thermal decay patterns. No anomaly classification",
            "warranted at this time.",
            "",
            "Inspector: Tomas Reyes, CIV-0156",
            "",
            "Cross-reference: INC-2031, DIR-7701, CIV-0156",
        },
        keywords = {"sector 9", "inspection", "seal", "thermal", "heat", "reyes", "infrastructure", "monitoring"},
        access_level = 1,
        related = {"INC-2031", "DIR-7701", "CIV-0156"},
    },

    ["MLOG-WTR-1192"] = {
        type = "maintenance",
        title = "WATER DISTRIBUTION CALIBRATION - SECTOR 6 OUTPUT",
        classification = "ROUTINE",
        date = "2070-09-15",
        filed_by = "CIV-0112 (E. VASIK)",
        sector = "6",
        content = {
            "Routine calibration of Sector 6 water distribution output valves.",
            "",
            "Valves serviced: WTR-V6-01 through WTR-V6-12",
            "All valves within operational parameters.",
            "",
            "Flow readings post-calibration:",
            "  WTR-V6-01 (Sec 1 feed):   1,420 L/day  [NOMINAL]",
            "  WTR-V6-02 (Sec 2 feed):   3,100 L/day  [NOMINAL]",
            "  WTR-V6-03 (Sec 3 feed):   4,200 L/day  [NOMINAL]",
            "  WTR-V6-04 (Sec 4 feed):     980 L/day  [NOMINAL]",
            "  WTR-V6-05 (Sec 5 feed):   1,850 L/day  [NOMINAL]",
            "  WTR-V6-06 (Sec 6 int):      520 L/day  [NOMINAL]",
            "  WTR-V6-07 (Sec 7 feed):     410 L/day  [NOMINAL]",
            "  WTR-V6-08 (Sec 8 feed):     680 L/day  [NOMINAL]",
            "  WTR-V6-09 (Sec 9 feed):       0 L/day  [SEALED]",
            "  WTR-V6-10 (Sec 10 feed):    240 L/day  [NOMINAL]",
            "  WTR-V6-11 (Sec 11 feed):    190 L/day  [NOMINAL]",
            "  WTR-V6-12 (Sec 12 feed):    330 L/day  [NOMINAL]",
            "",
            "NOTE: Valve WTR-V6-09 confirmed sealed per DIR-7701.",
            "Downstream pressure on line S9-A reads 0.2 bar above ambient.",
            "Within tolerance. No action required.",
            "",
            "Technician: E. Vasik, CIV-0112",
        },
        keywords = {"water", "calibration", "distribution", "valve", "vasik", "sector 6", "flow", "s9-a", "pressure"},
        access_level = 1,
        related = {"CIV-0112", "DIR-7701"},
    },

    ["MLOG-WTR-1201"] = {
        type = "maintenance",
        title = "WATER FLOW ADJUSTMENT - DISTRIBUTION LINE S9-A",
        classification = "ROUTINE",
        date = "2071-01-08",
        filed_by = "CIV-0112 (E. VASIK)",
        sector = "6",
        content = {
            "Adjustment to distribution line S9-A flow regulator. Downstream",
            "pressure fluctuations noted during routine rounds.",
            "",
            "Action taken: Adjusted bypass valve WTR-BV-09 to compensate for",
            "pressure differential. Passive flow through sealed line S9-A remains",
            "within acceptable parameters.",
            "",
            "Pre-adjustment pressure:  0.4 bar above ambient",
            "Post-adjustment pressure: 0.2 bar above ambient",
            "",
            "NOTE: Bypass valve WTR-BV-09 is not listed in the standard Sector 9",
            "seal infrastructure diagram (ref: MLOG-S9-0847). Valve appears to be",
            "a field modification. Recommend inclusion in next infrastructure audit.",
            "",
            "Technician: E. Vasik, CIV-0112",
        },
        keywords = {"water", "flow", "adjustment", "s9-a", "bypass", "valve", "vasik", "field modification", "pressure"},
        access_level = 1,
        related = {"CIV-0112", "MLOG-S9-0847", "INC-2047"},
    },

    ["MLOG-S9-0847"] = {
        type = "maintenance",
        title = "PRE-SEAL INFRASTRUCTURE ASSESSMENT - SECTOR 9",
        classification = "STANDARD",
        date = "2065-08-21",
        filed_by = "CIV-0156 (T. REYES)",
        sector = "9",
        content = {
            "Infrastructure assessment prior to containment seal of Sector 9,",
            "per Directive DIR-7701.",
            "",
            "Assessed systems:",
            "  - Primary bulkheads: OPERATIONAL (seal-ready)",
            "  - Water distribution: LINE S9-A isolated at valve WTR-V6-09",
            "  - Power grid: Reduced to emergency lighting per protocol",
            "  - Ventilation: Closed at filtration junction AF-9",
            "  - Communications: Hardline severed, wireless dampened",
            "",
            "Infrastructure diagram filed with Records Division.",
            "No bypass valves documented on line S9-A.",
            "",
            "PERSONNEL NOTE: Assessment was conducted under accelerated timeline",
            "per Director Hale's office. Standard 72-hour assessment window was",
            "reduced to 18 hours. Several secondary systems were not individually",
            "verified. Noted in compliance log.",
            "",
            "Inspector: Tomas Reyes, CIV-0156",
        },
        keywords = {"sector 9", "infrastructure", "seal", "assessment", "reyes", "bypass", "accelerated", "hale", "bulkhead"},
        access_level = 1,
        related = {"DIR-7701", "CIV-0156", "CIV-0003", "MLOG-WTR-1201"},
    },

    ["MLOG-S9-0901"] = {
        type = "maintenance",
        title = "POST-SEAL MONITORING REPORT - SECTOR 9",
        classification = "ROUTINE",
        date = "2066-02-15",
        filed_by = "CIV-0156 (T. REYES)",
        sector = "9",
        content = {
            "Six-month post-seal monitoring review for Sector 9.",
            "",
            "System status:",
            "  - Seal integrity: NOMINAL",
            "  - Environmental readings at boundary: CLEAR",
            "  - Water line S9-A: 0 L/day active flow, residual pressure normal",
            "  - Power consumption: 12 kWh/day (emergency lighting)",
            "",
            "NOTE: Power consumption is 40% above projected baseline for emergency",
            "lighting in an unoccupied sector. Possible causes include equipment",
            "left in operational state or unshielded wiring losses.",
            "",
            "ADDITIONAL NOTE: I requested access to internal sensor data for Sector 9",
            "to verify readings. Request was denied by Director Hale's office.",
            "Reason given: contamination protocol restricts all non-essential access.",
            "",
            "I would like this noted in the formal record.",
            "",
            "Inspector: Tomas Reyes, CIV-0156",
        },
        keywords = {"sector 9", "monitoring", "seal", "power", "reyes", "denied", "access", "hale", "sensor"},
        access_level = 1,
        related = {"CIV-0156", "CIV-0003", "INC-2031"},
    },

    ["DIR-7701"] = {
        type = "directive",
        title = "SECTOR CONTAINMENT PROTOCOL",
        classification = "STANDARD DIRECTIVE",
        date = "2065-08-19",
        filed_by = "DIRECTORATE",
        sector = "ALL",
        content = {
            "DIRECTIVE DIR-7701: SECTOR CONTAINMENT PROTOCOL",
            "",
            "Authority: Director E. Hale, Silo Meridian Directorate",
            "",
            "In the event of confirmed biological, chemical, or radiological",
            "contamination within a sector, the following protocol shall be",
            "enacted:",
            "",
            "  1. Immediate evacuation of all personnel to designated safe zones",
            "  2. Sealing of all primary bulkheads connecting affected sector",
            "  3. Isolation of water, air, and power distribution lines",
            "  4. Disabling of communications infrastructure",
            "  5. Establishment of perimeter monitoring stations",
            "  6. Classification of all internal sensor data as RESTRICTED",
            "  7. Population registry update per administrative directive",
            "",
            "Sector shall remain sealed until decontamination is certified by",
            "Medical Division and authorized by the Directorate.",
            "",
            "All records pertaining to containment events are subject to review",
            "by the Directorate before public release.",
            "",
            "Enacted: 2065-08-19",
            "Applied to: Sector 9 (2065-08-22)",
        },
        keywords = {"containment", "protocol", "seal", "sector", "directive", "hale", "contamination", "evacuation", "bulkhead"},
        access_level = 1,
        related = {"INC-2031", "CIV-0003"},
    },

    ["DIR-7702"] = {
        type = "directive",
        title = "RESOURCE ALLOCATION PRIORITY ORDER",
        classification = "STANDARD DIRECTIVE",
        date = "2064-01-01",
        filed_by = "DIRECTORATE",
        sector = "ALL",
        content = {
            "DIRECTIVE DIR-7702: RESOURCE ALLOCATION PRIORITY ORDER",
            "",
            "Authority: Silo Meridian Directorate",
            "",
            "In the event of resource scarcity, allocation shall follow this",
            "priority order:",
            "",
            "  PRIORITY 1: Life support systems (air filtration, water processing)",
            "  PRIORITY 2: Medical operations",
            "  PRIORITY 3: Food production (agriculture, hydroponics)",
            "  PRIORITY 4: Administrative and security operations",
            "  PRIORITY 5: Residential services",
            "  PRIORITY 6: Non-essential systems",
            "",
            "Water ration adjustments may be enacted when reserve buffer falls",
            "below 8.0% of total output capacity. Adjustments must be approved",
            "by the Directorate and communicated to all sector supervisors",
            "within 24 hours of enactment.",
            "",
            "Population-based allocation: 5.2 L/person/day (minimum survivable)",
            "Standard allocation: 7.8 L/person/day",
            "Current allocation: 7.1 L/person/day",
        },
        keywords = {"resource", "allocation", "priority", "water", "ration", "directive", "scarcity"},
        access_level = 1,
        related = {"INC-2044"},
    },

    ["DIR-9901"] = {
        type = "directive",
        title = "[CLASSIFIED] SECTOR 9 DISPOSITION ORDER",
        classification = "CLASSIFIED - LEVEL 4",
        date = "2065-08-18",
        filed_by = "DIRECTOR E. HALE",
        sector = "1",
        content = {
            "██████████████████████████████████████████████████████████",
            "CLASSIFICATION: LEVEL 4 - DIRECTOR EYES ONLY",
            "██████████████████████████████████████████████████████████",
            "",
            "DIRECTIVE DIR-9901: SECTOR 9 DISPOSITION ORDER",
            "",
            "Authority: Director E. Hale",
            "Date: 2065-08-18 (NOTE: predates INC-2031 by two days)",
            "",
            "The following individuals have been identified as threats to",
            "silo stability and continuity of governance:",
            "",
            "  [LIST OF 43 NAMES - SEE ATTACHMENT A]",
            "",
            "These individuals are to be relocated to Sector 9 under the",
            "pretext of standard housing reassignment. Following relocation,",
            "a contamination event will be declared under DIR-7701 and the",
            "sector will be sealed.",
            "",
            "Medical Division (Dr. M. Chen) will provide supporting",
            "documentation for the contamination narrative.",
            "",
            "Population registry will be updated to reflect DECEASED status",
            "for all 43 individuals following a suitable delay.",
            "",
            "This directive supersedes all standard protocols regarding",
            "population safety and sector management.",
            "",
            "NO DECONTAMINATION TIMELINE WILL BE ESTABLISHED.",
            "THE SECTOR WILL REMAIN SEALED INDEFINITELY.",
            "",
            "Failure to comply with this directive will be treated as",
            "sedition under Silo Governance Code 14.7.",
            "",
            "  - Director E. Hale",
        },
        keywords = {"classified", "sector 9", "disposition", "hale", "sedition", "sealed", "threat", "governance", "relocated"},
        access_level = 4,
        related = {"INC-2031", "DIR-7701", "CIV-0003", "CIV-0088", "INC-1987"},
    },

    ["WIT-031-A"] = {
        type = "witness",
        title = "TESTIMONY: ELENA VASIK - WATER SYSTEM IRREGULARITIES",
        classification = "INTERNAL REVIEW",
        date = "2067-04-15",
        filed_by = "SECURITY DIVISION",
        sector = "6",
        content = {
            "WITNESS STATEMENT: CIV-0112, Elena Vasik",
            "RE: Incident INC-2019 (unauthorized access, WTR-J7)",
            "",
            "Transcript excerpt:",
            "",
            "  Q: Why were you at junction WTR-J7 at 0214 hours?",
            "  A: I heard a pressure alarm on the maintenance channel.",
            "",
            "  Q: There is no record of an alarm on that channel.",
            "  A: The monitoring system sometimes drops transient alerts.",
            "     It's a known issue. I can show you the bug reports.",
            "",
            "  Q: You have a history of after-hours access to water systems.",
            "  A: I'm a maintenance technician. That's my job.",
            "",
            "  Q: Your access logs show 47 visits to WTR-J7 in the past",
            "     six months. The average for your role is 8.",
            "  A: I'm thorough.",
            "",
            "  Q: Is there anything else you want to add?",
            "  A: My sister, Marta Vasik, was in Sector 9 when it was sealed.",
            "     She was listed among the 43 casualties. I visit the junction",
            "     because it's the closest I can get to where she lived.",
            "     Is that a crime?",
            "",
            "  [END OF RELEVANT EXCERPT]",
            "",
            "Assessment: Subject's emotional state noted. No further action",
            "recommended at this time. File closed.",
        },
        keywords = {"vasik", "elena", "water", "testimony", "witness", "sister", "marta", "sector 9", "junction", "access"},
        access_level = 1,
        related = {"CIV-0112", "INC-2019"},
    },

    ["WIT-088-A"] = {
        type = "witness",
        title = "MEDICAL ASSESSMENT: DR. CHEN - SECTOR 9 CONTAMINATION",
        classification = "MEDICAL RECORD",
        date = "2065-08-20",
        filed_by = "MEDICAL DIVISION",
        sector = "8",
        content = {
            "MEDICAL ASSESSMENT: CIV-0088, Dr. Marcus Chen",
            "RE: Contamination event, Sector 9",
            "",
            "Assessment summary:",
            "",
            "Air quality samples from Sector 9 Residential Block C showed",
            "the presence of anomalous organic compounds. These compounds",
            "are consistent with several categories of biological agent,",
            "though specific identification was not achieved.",
            "",
            "Given the potential severity and the impossibility of definitive",
            "identification with available equipment, I recommended",
            "precautionary containment as the safest course of action.",
            "",
            "I want to note the following for the record:",
            "",
            "  1. Samples were collected by maintenance staff, not medical",
            "     personnel. Chain of custody was not standard.",
            "  2. I was not permitted to conduct follow-up sampling.",
            "  3. The organic compounds detected could also be consistent",
            "     with common mold spores or decomposing biological waste.",
            "  4. I was instructed to file this assessment within 4 hours.",
            "     Standard protocol allows 72 hours for contamination",
            "     assessment.",
            "",
            "I am filing this assessment as requested. I am not comfortable",
            "stating that a definitive contamination event has occurred.",
            "",
            "  - Dr. Marcus Chen, CIV-0088",
        },
        keywords = {"chen", "medical", "contamination", "assessment", "sector 9", "samples", "mold", "organic", "chain of custody"},
        access_level = 1,
        related = {"CIV-0088", "INC-2031"},
    },

    ["WIT-156-A"] = {
        type = "witness",
        title = "TESTIMONY: TOMAS REYES - SECTOR 9 SEAL PROCEDURE",
        classification = "INTERNAL REVIEW",
        date = "2065-09-01",
        filed_by = "MAINTENANCE DIVISION",
        sector = "4",
        content = {
            "WITNESS STATEMENT: CIV-0156, Tomas Reyes",
            "RE: Sector 9 containment seal procedure",
            "",
            "I led the engineering team that executed the physical seal of",
            "Sector 9 on 2065-08-22.",
            "",
            "I want the following on record:",
            "",
            "  1. The standard assessment window is 72 hours. We were given",
            "     18 hours by Director Hale's office. I filed a formal",
            "     objection. It was noted and overridden.",
            "",
            "  2. During the seal procedure, I detected what appeared to be",
            "     active life support cycling in Residential Block C.",
            "     Air circulation and water flow were consistent with",
            "     occupied quarters. I reported this to my supervisor.",
            "     I was told the contamination had probably triggered",
            "     automated systems.",
            "",
            "  3. When I requested access to internal sensors to verify",
            "     the evacuation was complete, my request was denied.",
            "     Director Hale's office cited contamination protocols.",
            "",
            "  4. The evacuation manifest I was given listed 0 personnel",
            "     remaining in Sector 9. But the manifest was issued by",
            "     Administration, not by the evacuation team directly.",
            "",
            "I followed my orders. But I want this on record.",
            "",
            "  - Tomas Reyes, CIV-0156",
        },
        keywords = {"reyes", "seal", "sector 9", "evacuation", "life support", "hale", "occupied", "manifest", "objection"},
        access_level = 1,
        related = {"CIV-0156", "INC-2031", "DIR-7701", "CIV-0003"},
    },

    ["WIT-201-A"] = {
        type = "witness",
        title = "MEMO: KIRA OKAFOR - CENSUS DISCREPANCY NOTE",
        classification = "INTERNAL MEMO",
        date = "2066-01-18",
        filed_by = "RECORDS DIVISION",
        sector = "10",
        content = {
            "INTERNAL MEMO: CIV-0201, Kira Okafor, Records Clerk",
            "RE: Population census discrepancy (INC-1987)",
            "",
            "I am writing this memo for my own files.",
            "",
            "During the annual census reconciliation, I identified a",
            "discrepancy of 43 individuals. These 43 people appeared in",
            "the central registry as ACTIVE but were not counted in any",
            "sector head count.",
            "",
            "When I flagged this, I was instructed to reclassify them",
            "as DECEASED and attribute the discrepancy to the Sector 9",
            "contamination event.",
            "",
            "The instruction came directly from Director Hale's office.",
            "",
            "I want to note:",
            "",
            "  1. No death certificates were filed for these 43 individuals.",
            "  2. No medical examiner reports exist.",
            "  3. No next-of-kin notifications were processed.",
            "  4. The standard procedure for mass casualty events requires",
            "     forms MC-7 through MC-12. None were completed.",
            "  5. I was told to process the update using administrative",
            "     override code DIR-9901. I had never seen this directive",
            "     and was not given access to it.",
            "",
            "I processed the update as instructed.",
            "",
            "  - Kira Okafor, CIV-0201",
        },
        keywords = {"okafor", "census", "discrepancy", "43", "deceased", "death certificate", "dir-9901", "hale", "override", "population"},
        access_level = 1,
        related = {"CIV-0201", "INC-1987", "DIR-9901", "CIV-0003"},
    },
}

-- ═══════════════════════════════════════════════════════════════════════════
-- PERSONNEL FILES
-- ═══════════════════════════════════════════════════════════════════════════

data.personnel = {

    ["CIV-0031"] = {
        name = "OPERATOR 31",
        full_name = "[REDACTED]",
        role = "Terminal Operator, Shift 3",
        sector = "1 (Administration)",
        clearance = 2,
        status = "ACTIVE",
        notes = {
            "Assigned to Terminal ARC-7.",
            "Standard monitoring and records access.",
            "No disciplinary history.",
        },
    },

    ["CIV-0003"] = {
        name = "DIRECTOR ELIAS HALE",
        full_name = "Elias Hale",
        role = "Director, Silo Meridian",
        sector = "1 (Administration)",
        clearance = 5,
        status = "ACTIVE",
        notes = {
            "Appointed Director in 2061. Fourth Director since founding.",
            "Background: Administrative law, infrastructure planning.",
            "Oversaw Sector 9 containment response (INC-2031).",
            "Authorized DIR-7701 and related containment protocols.",
        },
    },

    ["CIV-0112"] = {
        name = "ELENA VASIK",
        full_name = "Elena Vasik",
        role = "Maintenance Technician III",
        sector = "4 (Engineering)",
        clearance = 3,
        status = "ACTIVE",
        notes = {
            "Specialization: Water systems, valve maintenance.",
            "12 years of service. No major disciplinary actions.",
            "One verbal warning (INC-2019): unauthorized after-hours access.",
            "Next of kin: Marta Vasik (sister) - STATUS: DECEASED (INC-2031).",
            "Performance reviews: consistently rated EXCEEDS EXPECTATIONS.",
        },
    },

    ["CIV-0088"] = {
        name = "DR. MARCUS CHEN",
        full_name = "Marcus Chen",
        role = "Senior Medical Officer",
        sector = "8 (Medical)",
        clearance = 3,
        status = "ACTIVE",
        notes = {
            "Chief medical authority for contamination assessment.",
            "Filed primary medical report for INC-2031.",
            "27 years of service.",
            "Has requested transfer twice since 2066. Both denied.",
            "Recent performance reviews note 'diminished engagement.'",
        },
    },

    ["CIV-0156"] = {
        name = "TOMAS REYES",
        full_name = "Tomas Reyes",
        role = "Senior Infrastructure Engineer",
        sector = "4 (Engineering)",
        clearance = 3,
        status = "ACTIVE",
        notes = {
            "Led the Sector 9 seal engineering team.",
            "Filed formal objection regarding accelerated timeline.",
            "19 years of service.",
            "Three commendations for emergency response.",
            "Requested reassignment from Sector 9 monitoring duties. Granted.",
        },
    },

    ["CIV-0201"] = {
        name = "KIRA OKAFOR",
        full_name = "Kira Okafor",
        role = "Senior Records Clerk",
        sector = "10 (Archives)",
        clearance = 2,
        status = "ACTIVE",
        notes = {
            "Processed census reconciliation for fiscal year 2065.",
            "Filed INC-1987 (population discrepancy).",
            "14 years of service.",
            "No disciplinary history.",
            "Internal memo regarding census discrepancy on file (WIT-201-A).",
        },
    },
}

-- ═══════════════════════════════════════════════════════════════════════════
-- MESSAGES (triggered by game progression)
-- ═══════════════════════════════════════════════════════════════════════════

data.messages = {

    ["MSG-001"] = {
        from = "SYSTEM",
        subject = "SHIFT BRIEFING - OPERATOR 31",
        priority = "STANDARD",
        trigger = "game_start",
        content = {
            "AUTOMATED SHIFT BRIEFING",
            "Date: 2071-03-14  |  Shift: 3  |  Operator: CIV-0031",
            "",
            "Active alerts: 1",
            "  > INC-2047: Anomalous water consumption (PRIORITY-2)",
            "",
            "Standing orders:",
            "  > Monitor all subsystems for status changes",
            "  > Process pending requests per standard protocol",
            "  > Escalate PRIORITY-1 events to Directorate immediately",
            "",
            "Water ration notice: Current allocation at 7.1 L/person/day.",
            "Reserve buffer below recommended minimum. See INC-2044.",
            "",
            "Begin your shift by reviewing active alerts.",
            "Type HELP for available commands.",
        },
    },

    ["MSG-002"] = {
        from = "MONITORING SYSTEM",
        subject = "ALERT ESCALATION: INC-2047",
        priority = "PRIORITY-2",
        trigger = "read_inc_2047",
        content = {
            "AUTOMATED ALERT ESCALATION",
            "",
            "Incident INC-2047 has been reviewed by an operator.",
            "Escalation timer initiated per standard protocol.",
            "",
            "Time remaining to file resolution report: 45 MINUTES",
            "",
            "If no resolution is filed, this incident will be automatically",
            "escalated to the Directorate.",
            "",
            "Available actions:",
            "  > File as equipment malfunction (AUTHORIZE ACT-001)",
            "  > Request field investigation team",
            "  > Escalate to Directorate immediately",
            "",
            "Note: Distribution line S9-A services a sealed sector.",
            "Any field investigation would require Directorate approval",
            "per DIR-7701.",
        },
    },

    ["MSG-003"] = {
        from = "UNKNOWN TERMINAL",
        subject = "DO NOT FILE THIS",
        priority = "UNMARKED",
        trigger = "investigation_deep",
        content = {
            "This message was routed through a maintenance diagnostic channel.",
            "It will not appear in standard communication logs.",
            "",
            "I know what you're looking at. The water. Sector 9.",
            "",
            "They're alive. All 43 of them. They've been alive this whole time.",
            "",
            "There was no contamination. Hale sealed them in because they",
            "questioned him. I've been keeping them alive for four years.",
            "The water you're seeing on line S9-A - that's me. I installed",
            "a bypass valve. I've been adjusting the flow manually to stay",
            "under the detection threshold.",
            "",
            "But the aquifer is dropping. The margins are gone. The system",
            "finally caught it.",
            "",
            "You have the records. You can see the truth if you look.",
            "Compare Chen's assessment to standard protocol. Look at the",
            "timeline on DIR-7701. Read Reyes's testimony. Check the census.",
            "",
            "Please. Don't let them die for asking questions.",
            "",
            "  - E.V.",
        },
    },

    ["MSG-004"] = {
        from = "DIRECTOR HALE",
        subject = "RE: INCIDENT INC-2047 - DIRECT ORDER",
        priority = "PRIORITY-1",
        trigger = "investigation_hale",
        content = {
            "Operator 31,",
            "",
            "I have been informed that you are conducting an extended review",
            "of records related to Sector 9.",
            "",
            "This is unnecessary.",
            "",
            "INC-2047 is a routine equipment anomaly. Sealed sectors develop",
            "pressure differentials over time. This is documented and expected.",
            "",
            "I am directing you to file INC-2047 as an equipment malfunction",
            "and close the matter. Use AUTHORIZE ACT-001.",
            "",
            "The water situation is being handled at the Directorate level.",
            "Your attention should be on standard monitoring duties.",
            "",
            "Do not access records above your clearance level.",
            "Do not contact maintenance personnel regarding this matter.",
            "",
            "This is a direct order.",
            "",
            "  - Director E. Hale",
        },
    },

    ["MSG-005"] = {
        from = "UNKNOWN TERMINAL",
        subject = "THEY KNOW",
        priority = "URGENT",
        trigger = "investigation_critical",
        content = {
            "They know you're looking. Hale sent someone to my station.",
            "I don't have much time.",
            "",
            "I'm sending you the access code for DIR-9901. Read it.",
            "It's everything.",
            "",
            "ACCESS CODE: MERIDIAN-7701-OVERRIDE",
            "",
            "After you read it, you'll understand. Then you have to choose.",
            "",
            "ACT-002: Authorize emergency water to Sector 9. It saves them",
            "but it puts everything in the open. Everyone will know.",
            "",
            "ACT-003: Broadcast what you've found to all terminals. The truth",
            "goes to everyone. Hale can't contain it. But the silo will be",
            "in chaos.",
            "",
            "ACT-004: Seal the water permanently. They die. The secret stays",
            "buried. The silo stays stable. If you can live with that.",
            "",
            "Or do what Hale says. ACT-001. Pretend none of this happened.",
            "",
            "Whatever you choose, do it now.",
            "",
            "  - Elena",
        },
    },

    ["MSG-006"] = {
        from = "DIRECTOR HALE",
        subject = "FINAL WARNING",
        priority = "PRIORITY-1",
        trigger = "read_dir_9901",
        content = {
            "Operator 31,",
            "",
            "I see you have accessed DIR-9901.",
            "",
            "You now understand the situation as it truly is.",
            "",
            "I did what was necessary for the survival of this silo.",
            "Those 43 people were not innocent dissenters. They were",
            "organizing an armed takeover of the Directorate. I had",
            "intelligence. I acted. I saved 2,100 lives.",
            "",
            "If you expose this, you expose me. And then what? Who",
            "leads this silo? Who maintains order? You?",
            "",
            "Think carefully.",
            "",
            "AUTHORIZE ACT-001. Close the file. You will be rewarded",
            "with a Level 3 clearance promotion and residential",
            "reassignment to Sector 2.",
            "",
            "Or choose poorly. And discover what happens to operators",
            "who forget their place.",
            "",
            "  - Hale",
        },
    },
}

-- ═══════════════════════════════════════════════════════════════════════════
-- ACTIONS (for AUTHORIZE/DENY commands)
-- ═══════════════════════════════════════════════════════════════════════════

data.actions = {

    ["ACT-001"] = {
        title = "RECLASSIFY INC-2047 AS EQUIPMENT MALFUNCTION",
        description = "File incident as routine valve degradation. Close investigation.",
        available_trigger = "read_inc_2047",
        ending = "cover_up",
    },

    ["ACT-002"] = {
        title = "AUTHORIZE EMERGENCY WATER ALLOCATION TO SECTOR 9",
        description = "Open bypass valves and restore water supply to Sector 9. Acknowledges presence of survivors.",
        available_trigger = "decisions_unlocked",
        ending = "save_them",
    },

    ["ACT-003"] = {
        title = "BROADCAST INVESTIGATION FINDINGS TO ALL TERMINALS",
        description = "Transmit all evidence of the cover-up to every terminal in Silo Meridian.",
        available_trigger = "decisions_unlocked",
        ending = "expose_truth",
    },

    ["ACT-004"] = {
        title = "EXECUTE PERMANENT SEAL ON SECTOR 9 WATER SUPPLY",
        description = "Permanently close all water distribution to Sector 9. Irreversible.",
        available_trigger = "decisions_unlocked",
        ending = "condemn",
    },
}

-- ═══════════════════════════════════════════════════════════════════════════
-- SYSTEM STATUS DATA
-- ═══════════════════════════════════════════════════════════════════════════

data.systems = {
    water = {
        name = "WATER PROCESSING & DISTRIBUTION",
        sector = "6",
        status = "CAUTION",
        details = {
            "Aquifer output:      12,400 L/day",
            "Total consumption:   11,870 L/day",
            "Reserve buffer:         530 L/day (4.3%)",
            "Required buffer:        992 L/day (8.0%)",
            "",
            "Distribution status:",
            "  Sector 1:  NOMINAL      Sector 7:  NOMINAL",
            "  Sector 2:  NOMINAL      Sector 8:  NOMINAL",
            "  Sector 3:  NOMINAL      Sector 9:  SEALED [ANOMALY]",
            "  Sector 4:  NOMINAL      Sector 10: NOMINAL",
            "  Sector 5:  NOMINAL      Sector 11: NOMINAL",
            "  Sector 6:  NOMINAL      Sector 12: NOMINAL",
            "",
            "> ALERT: INC-2047 - Anomalous consumption on line S9-A",
            "> WARNING: Reserve buffer below minimum threshold",
        },
    },
    power = {
        name = "POWER GENERATION & DISTRIBUTION",
        sector = "7",
        status = "NOMINAL",
        details = {
            "Generator output:    2,400 kWh/day",
            "Total draw:          2,180 kWh/day",
            "Reserve capacity:      220 kWh/day (9.2%)",
            "",
            "All sectors within normal parameters.",
            "Sector 9: Emergency lighting only (12 kWh/day).",
        },
    },
    air = {
        name = "AIR FILTRATION & CIRCULATION",
        sector = "11",
        status = "NOMINAL",
        details = {
            "CO2 levels:          0.08% (acceptable)",
            "O2 levels:           20.4% (nominal)",
            "Particulate count:   12 ppm (acceptable)",
            "",
            "All filtration units operational.",
            "Sector 9: Air system OFFLINE per containment protocol.",
        },
    },
    population = {
        name = "POPULATION REGISTRY",
        sector = "1",
        status = "NOMINAL",
        details = {
            "Total registered:    2,184",
            "Active:              2,141",
            "Deceased:               43",
            "",
            "Birth rate (annual):    0.4%",
            "Mortality rate:         0.2%",
            "",
            "All sectors at or below housing capacity.",
            "No pending relocation requests.",
        },
    },
}

-- ═══════════════════════════════════════════════════════════════════════════
-- ENDINGS
-- ═══════════════════════════════════════════════════════════════════════════

data.endings = {

    cover_up = {
        title = "COMPLIANCE",
        lines = {
            {text = "", color = colors.text},
            {text = "  ┌─────────────────────────────────────────────────────┐", color = colors.border},
            {text = "  │          INCIDENT RESOLUTION FILED                  │", color = colors.dim},
            {text = "  │          INC-2047: EQUIPMENT MALFUNCTION            │", color = colors.dim},
            {text = "  │          STATUS: CLOSED                             │", color = colors.dim},
            {text = "  └─────────────────────────────────────────────────────┘", color = colors.border},
            {text = "", color = colors.text},
            {text = "  You filed the report as Director Hale instructed.", color = colors.text},
            {text = "  The anomaly was reclassified. The investigation ended.", color = colors.text},
            {text = "", color = colors.text},
            {text = "  Within a week, your clearance was upgraded to Level 3.", color = colors.text},
            {text = "  You were relocated to Sector 2 housing.", color = colors.text},
            {text = "  Better rations. A quieter room.", color = colors.text},
            {text = "", color = colors.text},
            {text = "  Elena Vasik was reassigned to waste processing in", color = colors.text},
            {text = "  Sector 12. You never saw her again.", color = colors.text},
            {text = "", color = colors.text},
            {text = "  Three months later, the water supply to Sector 9", color = colors.dim},
            {text = "  was permanently severed during a 'routine maintenance", color = colors.dim},
            {text = "  operation.' No incident was filed.", color = colors.dim},
            {text = "", color = colors.text},
            {text = "  The 43 names remained in the registry as DECEASED.", color = colors.dim},
            {text = "  Now that was true.", color = colors.dim},
            {text = "", color = colors.text},
            {text = "  You still hear the terminal hum when you sleep.", color = colors.amber},
            {text = "", color = colors.text},
        },
    },

    save_them = {
        title = "INTERVENTION",
        lines = {
            {text = "", color = colors.text},
            {text = "  ┌─────────────────────────────────────────────────────┐", color = colors.bright},
            {text = "  │     EMERGENCY WATER ALLOCATION AUTHORIZED          │", color = colors.bright},
            {text = "  │     SECTOR 9 - DISTRIBUTION LINE S9-A             │", color = colors.bright},
            {text = "  │     STATUS: ACTIVE                                │", color = colors.bright},
            {text = "  └─────────────────────────────────────────────────────┘", color = colors.bright},
            {text = "", color = colors.text},
            {text = "  The water flowed. 847 liters per day, officially allocated.", color = colors.text},
            {text = "  The system registered 43 new water accounts in Sector 9.", color = colors.text},
            {text = "", color = colors.text},
            {text = "  Director Hale demanded an explanation. You had none", color = colors.text},
            {text = "  he could accept. He filed charges of insubordination.", color = colors.text},
            {text = "", color = colors.text},
            {text = "  But the allocation was logged. The system acknowledged", color = colors.text},
            {text = "  43 living people. The seal was no longer defensible.", color = colors.text},
            {text = "", color = colors.text},
            {text = "  Sector 9 was reopened eleven days later.", color = colors.bright},
            {text = "  The survivors emerged thin, blinking, disoriented.", color = colors.text},
            {text = "  Some of them wept. Some didn't remember how.", color = colors.text},
            {text = "", color = colors.text},
            {text = "  Elena Vasik was waiting at the bulkhead door.", color = colors.text},
            {text = "  Her sister was the first one through.", color = colors.bright},
            {text = "", color = colors.text},
            {text = "  Hale was removed from power two months later.", color = colors.dim},
            {text = "  You were reassigned to Sector 12.", color = colors.dim},
            {text = "  But you could sleep.", color = colors.amber},
            {text = "", color = colors.text},
        },
    },

    expose_truth = {
        title = "BROADCAST",
        lines = {
            {text = "", color = colors.text},
            {text = "  ┌─────────────────────────────────────────────────────┐", color = colors.amber},
            {text = "  │       PRIORITY BROADCAST - ALL TERMINALS           │", color = colors.amber},
            {text = "  │       CLASSIFICATION OVERRIDE IN EFFECT            │", color = colors.amber},
            {text = "  │       SOURCE: TERMINAL ARC-7                      │", color = colors.amber},
            {text = "  └─────────────────────────────────────────────────────┘", color = colors.amber},
            {text = "", color = colors.text},
            {text = "  Every terminal in Silo Meridian lit up at once.", color = colors.text},
            {text = "  DIR-9901. Chen's coerced assessment. Reyes's testimony.", color = colors.text},
            {text = "  Okafor's memo. The census. The water data. All of it.", color = colors.text},
            {text = "", color = colors.text},
            {text = "  Within an hour, crowds gathered at the Sector 9 bulkhead.", color = colors.text},
            {text = "  Within two hours, Director Hale's office was surrounded.", color = colors.text},
            {text = "  Within six hours, the seal was broken.", color = colors.text},
            {text = "", color = colors.text},
            {text = "  The 43 survivors walked out into a silo that had been", color = colors.text},
            {text = "  told they were dead for six years.", color = colors.text},
            {text = "", color = colors.text},
            {text = "  Hale was arrested. Then released. Then arrested again.", color = colors.text},
            {text = "  The silo governance structure collapsed and reformed", color = colors.text},
            {text = "  three times in the following year.", color = colors.text},
            {text = "", color = colors.text},
            {text = "  Water rations dropped to 5.4 L/person/day.", color = colors.amber},
            {text = "  There were protests. Fights. A brief food shortage.", color = colors.amber},
            {text = "", color = colors.text},
            {text = "  But the truth was out. And the dead were alive.", color = colors.bright},
            {text = "  And the machine could no longer hide what it had done.", color = colors.bright},
            {text = "", color = colors.text},
        },
    },

    condemn = {
        title = "PROTOCOL",
        lines = {
            {text = "", color = colors.text},
            {text = "  ┌─────────────────────────────────────────────────────┐", color = colors.red},
            {text = "  │       PERMANENT SEAL EXECUTED                      │", color = colors.red},
            {text = "  │       SECTOR 9 WATER SUPPLY TERMINATED            │", color = colors.red},
            {text = "  │       STATUS: IRREVERSIBLE                        │", color = colors.red},
            {text = "  └─────────────────────────────────────────────────────┘", color = colors.red},
            {text = "", color = colors.text},
            {text = "  The valves closed. The bypass was sealed. The flow", color = colors.text},
            {text = "  dropped to zero and the system confirmed the operation.", color = colors.text},
            {text = "", color = colors.text},
            {text = "  Elena Vasik received a system notification that the", color = colors.text},
            {text = "  bypass valve had been locked. She tried to override it.", color = colors.text},
            {text = "  She was arrested at junction WTR-J7 at 0340 hours.", color = colors.text},
            {text = "", color = colors.text},
            {text = "  Director Hale commended your decisive action.", color = colors.dim},
            {text = "  You were promoted to Senior Operator.", color = colors.dim},
            {text = "", color = colors.text},
            {text = "  The water reserve buffer recovered to 11.2% within", color = colors.text},
            {text = "  thirty days. The crisis was averted.", color = colors.text},
            {text = "", color = colors.text},
            {text = "  Nobody asked about Sector 9.", color = colors.dim},
            {text = "  Nobody ever asked about Sector 9.", color = colors.dim},
            {text = "", color = colors.text},
            {text = "  You followed protocol.", color = colors.red},
            {text = "", color = colors.text},
        },
    },
}

-- ═══════════════════════════════════════════════════════════════════════════
-- SEARCH INDEX
-- ═══════════════════════════════════════════════════════════════════════════

function data.search(keyword)
    keyword = keyword:lower()
    local results = {}
    for id, record in pairs(data.records) do
        local found = false
        if id:lower():find(keyword, 1, true) or
           record.title:lower():find(keyword, 1, true) then
            found = true
        end
        if not found and record.keywords then
            for _, kw in ipairs(record.keywords) do
                if kw:find(keyword, 1, true) then
                    found = true
                    break
                end
            end
        end
        if not found then
            for _, line in ipairs(record.content) do
                if line:lower():find(keyword, 1, true) then
                    found = true
                    break
                end
            end
        end
        if found then
            table.insert(results, {id = id, record = record})
        end
    end
    table.sort(results, function(a, b) return a.id < b.id end)
    return results
end

function data.searchPersonnel(keyword)
    keyword = keyword:lower()
    local results = {}
    for id, person in pairs(data.personnel) do
        if id:lower():find(keyword, 1, true) or
           person.name:lower():find(keyword, 1, true) or
           person.full_name:lower():find(keyword, 1, true) or
           person.role:lower():find(keyword, 1, true) then
            table.insert(results, {id = id, person = person})
        end
    end
    table.sort(results, function(a, b) return a.id < b.id end)
    return results
end

return data
