local colors = require("colors")

local data = {}

data.records = {
    ["INC-7301"] = {
        type = "incident",
        title = "UNMETERED WATER DRAW - SERVICE SPINE A-17",
        classification = "PRIORITY-2",
        date = "2071-03-14",
        filed_by = "FLOW MONITOR DAEMON",
        sector = "6",
        proof = 1,
        content = {
            "Night monitoring flagged 612.4 L/day moving through retired manifold",
            "WTR-A17. The branch is mapped to Annex A-17, listed as decommissioned",
            "since the fire-isolation relocation of 2060-11-07.",
            "",
            "Expected flow:   0.0 L/day",
            "Observed flow: 612.4 L/day",
            "Pattern: smoothed manually across six-hour intervals",
            "",
            "The smoothing curve is inconsistent with passive leakage.",
            "Somebody is shaping the draw to stay beneath variance alarms.",
            "",
            "RECOMMENDATION: audit manifold history, retired branch maps, and any",
            "legacy nursery or quarantine allocations still attached to A-17.",
            "",
            "Cross-reference: MLOG-WTR-4408, INC-6402, DIR-4012",
        },
        keywords = {
            "water", "annex", "a-17", "draw", "manifold", "retired",
            "quarantine", "legacy branch", "flow", "smoothing",
        },
        related = {"MLOG-WTR-4408", "INC-6402", "DIR-4012"},
    },

    ["INC-7290"] = {
        type = "incident",
        title = "PEDIATRIC ANTIBIOTIC VARIANCE - MEDICAL LOCKER 3",
        classification = "PRIORITY-2",
        date = "2071-03-12",
        filed_by = "MEDICAL INVENTORY BOT",
        sector = "8",
        proof = 1,
        content = {
            "Thirty-one pediatric antibiotic courses are missing from MED-3 stock.",
            "Dispense trail terminates at legacy nursery code NUR-A17.",
            "",
            "Registry cross-check returned no active pediatric patients below age 5",
            "requiring these formulations in the public ledger.",
            "",
            "Related items missing in smaller quantities:",
            "  - glucose gel tubes",
            "  - fever reducers",
            "  - pediatric spacer masks",
            "",
            "Legacy destination NUR-A17 was retired on 2060-11-09.",
            "Automatic escalation was suppressed by a standing administrator mask.",
            "",
            "Cross-reference: MLOG-MED-1220, WIT-308-A",
        },
        keywords = {
            "pediatric", "antibiotic", "children", "nursery", "a-17",
            "med-3", "glucose", "mask", "legacy",
        },
        related = {"MLOG-MED-1220", "WIT-308-A"},
    },

    ["INC-7288"] = {
        type = "incident",
        title = "POPULATION REGISTRY CHECKSUM MISMATCH",
        classification = "PRIORITY-3",
        date = "2071-03-11",
        filed_by = "ARCHIVE INTEGRITY WATCHER",
        sector = "10",
        proof = 1,
        content = {
            "Nightly registry rebuild detected 64 unresolved leaf hashes present in",
            "the mirror tree but absent from the public population ledger.",
            "",
            "Branch label recovered before scrub: LANTERN",
            "Mirror depth: 4 levels",
            "Leaf count: 64",
            "",
            "Automated self-heal was denied by an administrator rule originating from",
            "Directorate node D-01. Suppression repeats every six hours.",
            "",
            "Registry mismatches of this size are not produced by ordinary clerical",
            "delay. They indicate a maintained shadow branch.",
            "",
            "Cross-reference: MLOG-ARC-0902, WIT-177-A",
        },
        keywords = {
            "population", "checksum", "registry", "lantern", "64",
            "shadow branch", "mirror", "directorate",
        },
        related = {"MLOG-ARC-0902", "WIT-177-A"},
    },

    ["INC-7021"] = {
        type = "incident",
        title = "CARBON SCRUBBER LOAD SPIKE - DORMANT AIR BRANCH",
        classification = "PRIORITY-2 [AUTO-CLOSED]",
        date = "2071-02-25",
        filed_by = "AIR QUALITY WATCHER",
        sector = "11",
        proof = 1,
        content = {
            "Air branch AF-A17, tagged DORMANT, consumed 18% more scrubber mass than",
            "its thermal model permits.",
            "",
            "Estimated respiration equivalent:",
            "  54-70 adults",
            "  or mixed adult/minor occupancy",
            "",
            "The branch was automatically closed under policy ANNEX-DORMANT-EXEMPT.",
            "No human operator reviewed the closure.",
            "",
            "Filter residue sample contained skin dust, cloth lint, candle carbon,",
            "and starch particulates.",
            "",
            "These are occupancy markers, not idle-system artifacts.",
            "",
            "Cross-reference: MLOG-AIR-4412, DIR-8890",
        },
        keywords = {
            "air", "scrubber", "carbon", "occupancy", "a-17", "dormant",
            "respiration", "children", "dust",
        },
        related = {"MLOG-AIR-4412", "DIR-8890"},
    },

    ["INC-6550"] = {
        type = "incident",
        title = "CIVIC DISTURBANCE - LANTERN ASSEMBLY",
        classification = "SECURITY PRIORITY-2 [ARCHIVED]",
        date = "2060-11-02",
        filed_by = "SECURITY DIVISION",
        sector = "2",
        proof = 1,
        content = {
            "Public disturbance at the ration queue outside Sector 2 exchange hall.",
            "A group self-identifying as the Lantern Assembly disrupted distribution",
            "while demanding disclosure of sealed ledgers, birth quotas, and surface",
            "survey data withheld by the Directorate.",
            "",
            "Crowd size estimate: 180",
            "Detained organizers: 13",
            "Fatalities: 3",
            "",
            "Recovered signage included the phrases:",
            '  "No more hidden mouths."',
            '  "Count the dead honestly."',
            "",
            "Administrative summary categorizes the assembly as a destabilization cell.",
            "",
            "Cross-reference: INC-6130, WIT-621-A",
        },
        keywords = {
            "lantern", "assembly", "protest", "ration", "riot", "surface",
            "hidden mouths", "dead", "security",
        },
        related = {"INC-6130", "WIT-621-A"},
    },

    ["INC-6130"] = {
        type = "incident",
        title = "SECURITY SUMMARY - EAST PUMP SABOTAGE CLAIM",
        classification = "SECURITY PRIORITY-1 [ARCHIVED]",
        date = "2060-11-05",
        filed_by = "CAPT. RHEA DRENN",
        sector = "6",
        proof = 1,
        content = {
            "Security intelligence asserted that Lantern Assembly members intended to",
            "force entry to East Pump Station and seize the public address node.",
            "",
            "Evidence recovered:",
            "  - two detonator housings",
            "  - one routing sketch of East Pump access ladders",
            "  - no confirmed explosive compound",
            "",
            "Recommendation from Security was immediate emergency powers and detention",
            "of all identified organizers pending interrogation.",
            "",
            "Note from filing officer: intent to sabotage cannot be proved from the",
            "materials recovered here alone.",
            "",
            "Cross-reference: INC-6550, WIT-621-A",
        },
        keywords = {
            "sabotage", "pump", "lantern", "detonator", "security",
            "emergency powers", "assembly",
        },
        related = {"INC-6550", "WIT-621-A"},
    },

    ["INC-6402"] = {
        type = "incident",
        title = "EMERGENCY FIRE ISOLATION RELOCATION - ANNEX A-17",
        classification = "RESTRICTED ANNEX FILE",
        date = "2060-11-07",
        filed_by = "DIRECTORATE OPERATIONS",
        sector = "1",
        proof = 2,
        requires_flag = "annex_vault_unlocked",
        lock_reason = "  Record sealed inside ANNEX occupancy branch. Rebuild and override required.",
        content = {
            "Forty-three adults linked to Lantern Assembly logistics were relocated to",
            "Annex A-17 under emergency fire-isolation authority.",
            "",
            "Additional relocated support staff:",
            "  - Elsa Kell, nursery aide",
            "  - Marek Sorn, sanitation porter",
            "",
            "Public rationale: smoke contamination in housing corridor C-2.",
            "Operational duration listed on intake form: 48 hours.",
            "",
            "Family tracing, legal review, and external notice were suspended by",
            "Director's seal pending stabilization.",
            "",
            "No release order is attached to this file.",
            "",
            "Cross-reference: DIR-8890, WIT-308-A",
        },
        keywords = {
            "relocation", "fire isolation", "a-17", "43", "elsa kell",
            "lantern", "48 hours", "support staff",
        },
        related = {"DIR-8890", "WIT-308-A"},
    },

    ["INC-7316"] = {
        type = "incident",
        title = "WINTER RATION MODEL - OFF-LEDGER POPULATION +64",
        classification = "ANALYTIC OUTPUT",
        date = "2071-03-14",
        filed_by = "RESOURCE MODELER",
        sector = "1",
        proof = 2,
        requires_flag = "model_generated",
        lock_reason = "  Run the off-ledger ration model before this file exists.",
        content = {
            "Projection assumes 64 hidden residents in Annex A-17, including minors",
            "with elevated respiratory and nutritional needs.",
            "",
            "Outcome bands through late winter:",
            "",
            "  QUIET LIQUIDATION OF ANNEX",
            "    External additional deaths: 0",
            "    Annex deaths: 64",
            "",
            "  COVERT SUPPORT, PUBLIC LEFT UNINFORMED",
            "    External additional deaths: 9",
            "    Chronic weakness cases: 113",
            "",
            "  CONTROLLED DISCLOSURE + RATION CUT TO 5.6 L/DAY",
            "    External additional deaths: 17",
            "    Unrest probability: 34%",
            "",
            "  FULL BROADCAST + OPENING BULKHEADS",
            "    External additional deaths: 41",
            "    Governance failure probability: 61%",
            "",
            "There is no option in this model that preserves every life.",
            "",
            "Cross-reference: DIR-4012, DIR-9991, WIT-214-A",
        },
        keywords = {
            "winter", "ration", "model", "64", "deaths", "bulkheads",
            "off-ledger", "annex", "governance failure",
        },
        related = {"DIR-4012", "DIR-9991", "WIT-214-A"},
    },

    ["MLOG-WTR-4408"] = {
        type = "maintenance",
        title = "BLACK MANIFOLD BACKWASH - WTR-A17",
        classification = "ROUTINE",
        date = "2071-03-08",
        filed_by = "CIV-0119 (N. SOL)",
        sector = "6",
        proof = 1,
        content = {
            "Backwashed mineral grit from retired black manifold feeding A-17.",
            "",
            "The branch should have been dry.",
            "It was not.",
            "",
            "Observed pressure oscillation suggests hand-tuned restriction at three",
            "separate points instead of a single failed seal.",
            "",
            "If nobody is touching the branch, then the branch has learned to lie.",
            "",
            "Supervisor signoff missing from copied ledger image.",
            "Manual note in margin: keep the curve smooth or the night daemon sees it.",
            "",
            "Cross-reference: INC-7301",
        },
        keywords = {
            "water", "manifold", "black pipe", "a-17", "naima", "curve",
            "daemon", "pressure", "backwash",
        },
        related = {"INC-7301"},
    },

    ["MLOG-AIR-4412"] = {
        type = "maintenance",
        title = "SCRUBBER CASSETTE REPLACEMENT - AF-A17",
        classification = "ROUTINE",
        date = "2071-02-26",
        filed_by = "AIR SYSTEMS BOT",
        sector = "11",
        proof = 1,
        content = {
            "Replaced carbon cassette on branch AF-A17 after saturation threshold was",
            "reached 41 days earlier than forecast.",
            "",
            "Residue summary:",
            "  - candle carbon",
            "  - skin dust",
            "  - cloth fibers",
            "  - cooked starch particulates",
            "",
            "Dormant annex branches are not expected to produce any of the above.",
            "",
            "This log was tagged for auto-erasure under ANNEX-DORMANT-EXEMPT but the",
            "erase callback failed on first attempt.",
            "",
            "Cross-reference: INC-7021",
        },
        keywords = {
            "air", "scrubber", "candle", "cloth", "starch", "a-17",
            "dormant annex", "erase callback",
        },
        related = {"INC-7021"},
    },

    ["MLOG-MED-1220"] = {
        type = "maintenance",
        title = "LEGACY NURSERY BIN RESTOCK - NUR-A17",
        classification = "ROUTINE",
        date = "2071-03-09",
        filed_by = "CIV-0084 (I. SERA)",
        sector = "8",
        proof = 1,
        content = {
            "Restocked retired nursery bin NUR-A17 with small-dose antibiotics, fever",
            "reducers, spacer masks, and glucose gel.",
            "",
            "Collection authenticated by badge:",
            "  CIV-0308 (ELSA KELL)",
            "",
            "Personnel registry marks CIV-0308 as DECEASED since 2061.",
            "",
            "This discrepancy was not escalated. The cart left at 0213 through med",
            "corridor C under silent access rules.",
            "",
            "Cross-reference: INC-7290, WIT-308-A",
        },
        keywords = {
            "nursery", "children", "a-17", "elsa kell", "deceased badge",
            "antibiotics", "silent access",
        },
        related = {"INC-7290", "WIT-308-A"},
    },

    ["MLOG-ARC-0902"] = {
        type = "maintenance",
        title = "ARCHIVE MIRROR CHECKSUM DRIFT - LANTERN BRANCH",
        classification = "ROUTINE",
        date = "2071-03-11",
        filed_by = "CIV-0177 (J. BELL)",
        sector = "10",
        proof = 1,
        content = {
            "Mirror rebuild encountered a hidden branch header labeled LANTERN before",
            "the directorate scrubber reaped it.",
            "",
            "Recovered values:",
            "  branch depth: 4",
            "  leaf count: 64",
            "  parent path: ANNEX/OCCUPANCY",
            "",
            "A manual checksum re-tree might restore the branch long enough to pull a",
            "valid override token from the old index table.",
            "",
            "It will also trip audit alarms.",
            "",
            "Cross-reference: INC-7288, WIT-177-A",
        },
        keywords = {
            "archive", "mirror", "checksum", "lantern", "override token",
            "annex occupancy", "audit", "jonas bell",
        },
        related = {"INC-7288", "WIT-177-A"},
    },

    ["MLOG-ANN-0007"] = {
        type = "maintenance",
        title = "ANNEX A-17 INGRESS POWER TEST",
        classification = "RESTRICTED ANNEX FILE",
        date = "2071-03-01",
        filed_by = "DIRECTORATE OPERATIONS",
        sector = "1",
        proof = 2,
        requires_flag = "annex_vault_unlocked",
        lock_reason = "  Record sealed inside ANNEX occupancy branch. Rebuild and override required.",
        content = {
            "Door magnetics for A-17 were energized for 90 seconds during crate intake.",
            "",
            "Budgeted load attached to ingress cycle:",
            "  - 64 bunks",
            "  - 3 warm cabinets",
            "  - 1 classroom strip",
            "  - 1 wash pump",
            "",
            "Pickup microphone caught the following before mute engaged:",
            '  "Count to nine then run."',
            '  "[child laughing]"',
            "",
            "These are not the sounds of a dead annex.",
            "",
            "Cross-reference: DIR-8890, WIT-777-A",
        },
        keywords = {
            "ingress", "door", "64 bunks", "classroom", "children",
            "count to nine", "a-17",
        },
        related = {"DIR-8890", "WIT-777-A"},
    },

    ["DIR-4012"] = {
        type = "directive",
        title = "SCARCITY TRIAGE LADDER",
        classification = "STANDARD DIRECTIVE",
        date = "2062-01-03",
        filed_by = "DIRECTORATE",
        sector = "ALL",
        proof = 1,
        content = {
            "In periods of resource scarcity, preservation order is as follows:",
            "",
            "  1. air circulation and scrubber continuity",
            "  2. potable water and pump integrity",
            "  3. trauma and infection response",
            "  4. nursery and neonatal support",
            "  5. public ration stability",
            "  6. archives and civic administration",
            "",
            "Unregistered population carries no formal standing claim.",
            "Emergency exceptions require a Director's seal.",
            "",
            "Cross-reference: INC-7316",
        },
        keywords = {
            "scarcity", "triage", "directive", "unregistered population",
            "rations", "water", "neonatal", "director",
        },
        related = {"INC-7316"},
    },

    ["DIR-4980"] = {
        type = "directive",
        title = "COGNITIVE QUIETING ADDITIVE GUIDELINE",
        classification = "RESTRICTED ANNEX FILE",
        date = "2061-02-17",
        filed_by = "DIRECTORATE MEDICAL POLICY",
        sector = "8",
        proof = 2,
        requires_flag = "annex_vault_unlocked",
        lock_reason = "  Record sealed inside ANNEX occupancy branch. Rebuild and override required.",
        content = {
            "Low-dose calm-ash additive may be introduced to reclaimed water in",
            "quarantine populations to reduce panic, agitation, and organized refusal.",
            "",
            "Observed effects under prolonged use:",
            "  - memory flattening",
            "  - speech delay in minors",
            "  - affect blunting",
            "  - lowered aggression and initiative",
            "",
            "Directive note: outcomes are acceptable where obedience is the primary",
            "clinical requirement.",
            "",
            "Minors exposed for more than 18 months may never fully recover baseline",
            "cognitive range.",
            "",
            "Cross-reference: WIT-084-A, DIR-9104",
        },
        keywords = {
            "calm ash", "sedative", "children", "minors", "memory",
            "obedience", "quarantine", "cognitive",
        },
        related = {"WIT-084-A", "DIR-9104"},
    },

    ["DIR-8890"] = {
        type = "directive",
        title = "ANNEX OCCUPANCY SUPPRESSION ORDER",
        classification = "RESTRICTED ANNEX FILE",
        date = "2060-11-08",
        filed_by = "DIRECTOR ORLA VEY",
        sector = "1",
        proof = 3,
        requires_flag = "annex_vault_unlocked",
        lock_reason = "  Record sealed inside ANNEX occupancy branch. Rebuild and override required.",
        content = {
            "Occupants of Annex A-17 are to be removed from visible ledgers and kept",
            "at minimum survivable intake until further notice.",
            "",
            "Administrative handling:",
            "  - public status: deceased or relocated",
            "  - births: unrecorded",
            "  - education: literacy, counting, obedience only",
            "  - movement: corridor-restricted",
            "",
            "The purpose of A-17 is not punishment alone.",
            "It is proof that disorder can be made to disappear without spectacle.",
            "",
            "No release order is to be drafted without direct approval from this office.",
            "",
            "  - Orla Vey",
        },
        keywords = {
            "suppression", "annex", "births unrecorded", "obedience",
            "deceased", "orla vey", "a-17",
        },
        related = {"INC-6402", "DIR-4980"},
    },

    ["DIR-9104"] = {
        type = "directive",
        title = "ASHLINE DOCTRINE",
        classification = "BLACK VAULT",
        date = "2061-06-22",
        filed_by = "DIRECTORATE CONTINUITY CELL",
        sector = "1",
        proof = 4,
        requires_flag = "doctrine_unlocked",
        lock_reason = "  BLACK VAULT locked. Deep override required.",
        content = {
            "Founding doctrine for long-scarcity governance:",
            "",
            "Total truth is incompatible with durable obedience.",
            "",
            "Where dissent clusters form, move them below memory horizon rather than",
            "making martyrs of them. Sustain them cheaply. Let rumor decay into myth.",
            "",
            "A hidden population serves three functions:",
            "  1. pressure buffer during shortages",
            "  2. cautionary absence for the public",
            "  3. proof that mercy can be rationed",
            "",
            'Doctrine margin note: "Mercy that can be denied is cleaner than revolt."',
            "",
            "Cross-reference: DIR-4980, DIR-9991",
        },
        keywords = {
            "ashline", "doctrine", "hidden population", "mercy",
            "revolt", "obedience", "pressure buffer",
        },
        related = {"DIR-4980", "DIR-9991"},
    },

    ["DIR-9991"] = {
        type = "directive",
        title = "ANNEX LIQUIDATION CONTINGENCY",
        classification = "BLACK VAULT",
        date = "2068-01-14",
        filed_by = "DIRECTORATE CONTINUITY CELL",
        sector = "1",
        proof = 4,
        requires_flag = "doctrine_unlocked",
        lock_reason = "  BLACK VAULT locked. Deep override required.",
        content = {
            "If Annex A-17 exceeds cost curve or discovery becomes probable, enact the",
            "following sequence within six minutes:",
            "",
            "  1. chlorine pulse through black manifold",
            "  2. archive scrub of ANNEX/OCCUPANCY tree",
            "  3. nurse retained operators through post-event silence period",
            "",
            "Legacy dependents are not to be counted separately.",
            "No body recovery is required.",
            "",
            "If questioned publicly, classify the event as mineral purge and failed",
            "seal maintenance on a dead branch.",
            "",
            "Cross-reference: DIR-9104, INC-7316",
        },
        keywords = {
            "liquidation", "chlorine", "annex", "children", "legacy dependents",
            "silence", "mineral purge",
        },
        related = {"DIR-9104", "INC-7316"},
    },

    ["WIT-084-A"] = {
        type = "witness",
        title = "MEDICAL OBJECTION: DR. ILYA SERA",
        classification = "INTERNAL MEMO",
        date = "2062-04-03",
        filed_by = "MEDICAL DIVISION",
        sector = "8",
        proof = 1,
        content = {
            "I object to long-term calm-ash exposure in minors.",
            "",
            "You do not get quiet children.",
            "You get blunted children who stop forming time correctly.",
            "",
            "They lose words first. Then sequence. Then appetite for play.",
            "A child should not sound sedated while learning to count.",
            "",
            "If A-17 is still active, and I believe it is, this directive is not",
            "containment medicine. It is developmental damage written as procedure.",
            "",
            "  - Dr. Ilya Sera",
        },
        keywords = {
            "sera", "medical", "calm ash", "children", "sequence",
            "count", "developmental damage", "a-17",
        },
        related = {"DIR-4980"},
    },

    ["WIT-177-A"] = {
        type = "witness",
        title = "PRIVATE NOTE: JONAS BELL",
        classification = "INTERNAL MEMO",
        date = "2071-03-11",
        filed_by = "ARCHIVE DIVISION",
        sector = "10",
        proof = 1,
        content = {
            "Sixty-four orphan hashes do not appear by accident.",
            "",
            "Someone is gardening the dead.",
            "",
            "The scrubber does not delete that branch because it is corrupted.",
            "It deletes it because the branch is alive enough to be dangerous.",
            "",
            "I am leaving this note in a routine bucket because fear makes people",
            "write in the wrong places. Maybe that is the only reason anything survives.",
            "",
            "  - J.B.",
        },
        keywords = {
            "jonas", "bell", "64", "gardening the dead", "scrubber",
            "lantern", "branch alive",
        },
        related = {"INC-7288", "MLOG-ARC-0902"},
    },

    ["WIT-214-A"] = {
        type = "witness",
        title = "RESOURCE NOTE: LEON VAR",
        classification = "INTERNAL MEMO",
        date = "2071-03-13",
        filed_by = "RESOURCE MODELING",
        sector = "1",
        proof = 1,
        content = {
            "If there is a hidden population above fifty, then winter planning is already",
            "wrong by an amount that kills people.",
            "",
            "Not dramatically. That would at least be honest.",
            "",
            "Quietly. Dialysis gets shorter. Nursery meals thin out. Filter swaps slip.",
            "People who were not in the room for the decision die months later and the",
            "spreadsheet calls it trend noise.",
            "",
            "There is no clean allocation left in this silo.",
            "",
            "  - Leon Var",
        },
        keywords = {
            "leon var", "hidden population", "winter", "spreadsheet",
            "dialysis", "nursery meals", "allocation",
        },
        related = {"INC-7316", "DIR-4012"},
    },

    ["WIT-308-A"] = {
        type = "witness",
        title = "TRANSFER OBJECTION: ELSA KELL",
        classification = "INTERNAL REVIEW",
        date = "2060-11-07",
        filed_by = "NURSERY ADMIN",
        sector = "3",
        proof = 2,
        content = {
            "I was ordered to accompany two feverish infants and one story slate to",
            "Annex A-17 for a relocation listed as forty-eight hours.",
            "",
            "If this is truly smoke isolation, why are we sending alphabet cards, spare",
            "blankets, and a hand-crank lesson lamp?",
            "",
            "I want it noted that one infant is too small for the blankets assigned and",
            "that neither family was permitted to come to intake.",
            "",
            "No one answered me.",
            "",
            "  - Elsa Kell",
        },
        keywords = {
            "elsa kell", "nursery", "infants", "alphabet cards", "a-17",
            "blankets", "forty-eight hours",
        },
        related = {"INC-6402", "MLOG-MED-1220"},
    },

    ["WIT-621-A"] = {
        type = "witness",
        title = "SEALED DEPOSITION: CAPT. RHEA DRENN",
        classification = "INTERNAL REVIEW",
        date = "2061-01-12",
        filed_by = "SECURITY OVERSIGHT",
        sector = "4",
        proof = 2,
        content = {
            "Yes, the Lantern Assembly meant to force a confrontation.",
            "No, I cannot prove they planned mass murder.",
            "",
            "After three protesters died in the queue crush, several of them said the",
            "pump room was the only place left anyone would listen.",
            "",
            "Some brought tools. One talked about shutting the pumps long enough to make",
            "the whole silo hear the silence. That is not the same thing as wanting to",
            "kill two thousand people.",
            "",
            "We called them terrorists because it closed the argument.",
            "",
            "  - Capt. Rhea Drenn",
        },
        keywords = {
            "rhea drenn", "lantern", "terrorists", "pump room", "silence",
            "security", "protesters",
        },
        related = {"INC-6550", "INC-6130"},
    },

    ["WIT-777-A"] = {
        type = "witness",
        title = "TRANSCRIBED SLATE FRAGMENT - A-17 CLASSROOM",
        classification = "LIVE ANNEX CAPTURE",
        date = "2071-03-14",
        filed_by = "AUDIO RESTORE",
        sector = "A-17",
        proof = 3,
        requires_flag = "camera_looped",
        lock_reason = "  Capture a live slate sync from A-17 before this file exists.",
        content = {
            'VOICE 1 (child, female): "Do outside people dream in color?"',
            'VOICE 2 (adult, female): "Sometimes. Keep counting."',
            "",
            'VOICE 1: "Why do we count pipes?"',
            'VOICE 2: "Because every number is proof we are still here."',
            "",
            'VOICE 1: "What is dead?"',
            'VOICE 2: "A word they used when they shut the first door."',
            "",
            "[audio loss]",
            "",
            "There are pauses in the transcript where the child appears to wait for",
            "permission to ask obvious things.",
            "",
            "Cross-reference: MLOG-ANN-0007, DIR-4980",
        },
        keywords = {
            "classroom", "child", "dream in color", "count pipes",
            "dead", "audio", "a-17",
        },
        related = {"MLOG-ANN-0007", "DIR-4980"},
    },

    ["INC-6117"] = {
        type = "incident",
        title = "UP-SHAFT SURVEY LOSS - TEAM KESTREL",
        classification = "BLACK VAULT",
        date = "2061-05-14",
        filed_by = "EXTERNAL OPERATIONS",
        sector = "SURFACE ACCESS",
        proof = 3,
        requires_flag = "dawn_vault_unlocked",
        lock_reason = "  DAWN branch locked. Surface continuity records remain suppressed.",
        content = {
            "Survey Team Kestrel reached West Mast 4 during a low-particulate weather",
            "window and transmitted eleven minutes of exterior telemetry before life",
            "support failed on ascent return.",
            "",
            "Transmission summary:",
            "  - breathable interval measured at 9m 14s",
            "  - light level exceeded projected lethal haze thresholds",
            "  - fungal particulate surge followed window closure by 17m",
            "",
            "Public cause of death was recorded as routine shaft collapse training.",
            "",
            "One final voice packet from Surveyor Mara Quill was detached from the",
            "official archive and reclassified under continuity privilege.",
            "",
            "Cross-reference: WIT-412-A, DIR-8700",
        },
        keywords = {
            "surface", "survey", "kestrel", "west mast", "particulate",
            "breathable", "mara quill", "shaft", "telemetry",
        },
        related = {"WIT-412-A", "DIR-8700"},
    },

    ["INC-7322"] = {
        type = "incident",
        title = "EXTERNAL TELEMETRY PHASE WINDOW - WEST MAST 4",
        classification = "PRIORITY-2",
        date = "2071-03-14",
        filed_by = "EXTERNAL SENSOR WATCHER",
        sector = "SURFACE ACCESS",
        proof = 1,
        content = {
            "Retired mast WM-4 reported a nine-second clean-signal interval before",
            "Directorate suppressor rule D-DAWN-4 forced the channel dark.",
            "",
            "Captured values before closure:",
            "  - airborne toxin index: low-transient",
            "  - spore density: subcritical for 6.1 seconds",
            "  - luminance: above dead-sky baseline",
            "",
            "Automatic annotation marked the packet as 'sensor drift due to mast rot.'",
            "The values do not resemble mast rot.",
            "",
            "Cross-reference: MLOG-EXT-4401, MLOG-SRF-2003",
        },
        keywords = {
            "external", "wm-4", "west mast", "signal", "clean interval",
            "dawn", "surface", "spore density",
        },
        related = {"MLOG-EXT-4401", "MLOG-SRF-2003"},
    },

    ["INC-7336"] = {
        type = "incident",
        title = "SURFACE STABILITY MODEL - WINDOW ACCESS SCENARIO",
        classification = "ANALYTIC OUTPUT",
        date = "2071-03-14",
        filed_by = "RESOURCE MODELER",
        sector = "1",
        proof = 2,
        requires_flag = "surface_model_generated",
        lock_reason = "  Run the surface stability model before this file exists.",
        content = {
            "Combined model based on Team Kestrel telemetry, WM-4 residual packets,",
            "and current respiratory reserve.",
            "",
            "Projected scenarios:",
            "",
            "  MAINTAIN SUBTERRANEAN STATUS QUO",
            "    Short-term deaths: lowest",
            "    Long-term governance violence: sustained",
            "",
            "  LIMITED DAWN CORRIDOR OPENING",
            "    Immediate deaths from crowding/panic: 8-19",
            "    Medium-term survivability gain if discipline holds: moderate",
            "",
            "  FULL PUBLIC SURFACE BROADCAST",
            "    Immediate deaths from rush/failure: 27-63",
            "    Chance of irreversible political fracture: high",
            "",
            "The surface is not paradise.",
            "It is not dead either.",
            "",
            "Cross-reference: INC-6117, DIR-8700, DIR-9408",
        },
        keywords = {
            "surface model", "window access", "broadcast", "rush",
            "political fracture", "not dead", "dawn",
        },
        related = {"INC-6117", "DIR-8700", "DIR-9408"},
    },

    ["MLOG-EXT-4401"] = {
        type = "maintenance",
        title = "LOW-POWER HANDSHAKE - WEST MAST 4",
        classification = "ROUTINE",
        date = "2071-03-10",
        filed_by = "EXTERNAL GRID BOT",
        sector = "SURFACE ACCESS",
        proof = 1,
        content = {
            "Dormant mast WM-4 requested handshake power at 03:11 and 03:19 during",
            "storm lull conditions.",
            "",
            "Handshake origin is impossible under the public infrastructure map.",
            "The mast should be dark and fused.",
            "",
            "Suppression mask D-DAWN-4 prevented escalation and tagged the event as",
            "'legacy chatter'.",
            "",
            "Legacy structures do not ask permission twice in eight minutes.",
            "",
            "Cross-reference: INC-7322, MLOG-SRF-2003",
        },
        keywords = {
            "west mast", "handshake", "legacy chatter", "dawn", "external grid",
            "surface", "storm lull",
        },
        related = {"INC-7322", "MLOG-SRF-2003"},
    },

    ["MLOG-SRF-2003"] = {
        type = "maintenance",
        title = "UNSCHEDULED POWER REROUTE - WEST MAST 4",
        classification = "BLACK VAULT",
        date = "2069-08-04",
        filed_by = "DIRECTORATE OPERATIONS",
        sector = "7",
        proof = 2,
        requires_flag = "doctrine_unlocked",
        lock_reason = "  BLACK VAULT locked. Deep override required.",
        content = {
            "Power was silently rerouted from decommissioned classroom strips and dead",
            "lift coils to maintain heartbeat current on WM-4 and the shaft lock servo.",
            "",
            "Justification field:",
            '  "Preserve dawn option without public signal trail."',
            "",
            "Load was hidden inside annex maintenance budgets and mislabeled as heating",
            "loss on retired corridors.",
            "",
            "Cross-reference: INC-7322, DIR-9408",
        },
        keywords = {
            "power reroute", "west mast", "dawn option", "servo",
            "surface", "heartbeat current", "annex budget",
        },
        related = {"INC-7322", "DIR-9408"},
    },

    ["DIR-8700"] = {
        type = "directive",
        title = "VERTICAL CONTAINMENT NARRATIVE STANDARD",
        classification = "BLACK VAULT",
        date = "2061-05-20",
        filed_by = "DIRECTOR ORLA VEY",
        sector = "1",
        proof = 4,
        requires_flag = "dawn_vault_unlocked",
        lock_reason = "  DAWN branch locked. Surface continuity records remain suppressed.",
        content = {
            "Public doctrine shall hold that the surface is uniformly fatal and offers",
            "no actionable survival window.",
            "",
            "Internal exception:",
            "  intermittent breathable intervals may occur in narrow storm troughs",
            "",
            "Reason for suppression:",
            "  mass knowledge of intervals creates ungovernable ascent pressure",
            "",
            "Instruction:",
            "  destroy optimism before it organizes",
            "",
            "The silo survives by certainty. Accuracy is a separate question.",
            "",
            "Cross-reference: INC-6117, DIR-9408",
        },
        keywords = {
            "surface", "narrative", "fatal", "breathable intervals",
            "optimism", "ascent pressure", "certainty",
        },
        related = {"INC-6117", "DIR-9408"},
    },

    ["DIR-9408"] = {
        type = "directive",
        title = "DAWN COHORT EVALUATION",
        classification = "BLACK VAULT",
        date = "2069-08-05",
        filed_by = "DIRECTORATE CONTINUITY CELL",
        sector = "1",
        proof = 4,
        requires_flag = "dawn_vault_unlocked",
        lock_reason = "  DAWN branch locked. Surface continuity records remain suppressed.",
        content = {
            "A-17 minors demonstrate unusual compliance, low attachment to public",
            "social structures, and controlled educational baselines.",
            "",
            "Continuity proposal:",
            "  if a stable ascent window emerges, first surface cohort should be drawn",
            "  from annex youth and guided staff rather than the public population",
            "",
            "Operational advantages:",
            "  - reduced kin backlash in main silo",
            "  - better obedience under deprivation",
            "  - no public expectation of equal access",
            "",
            "Margin note:",
            '  "They were hidden for governance. They may yet justify the hiding."',
            "",
            "Cross-reference: MLOG-SRF-2003, WIT-940-A",
        },
        keywords = {
            "dawn cohort", "surface cohort", "annex youth", "obedience",
            "equal access", "hidden children", "governance",
        },
        related = {"MLOG-SRF-2003", "WIT-940-A"},
    },

    ["WIT-412-A"] = {
        type = "witness",
        title = "VOICE PACKET: MARA QUILL - FINAL SURVEY",
        classification = "BLACK VAULT",
        date = "2061-05-14",
        filed_by = "AUDIO RESTORE",
        sector = "SURFACE ACCESS",
        proof = 3,
        requires_flag = "dawn_vault_unlocked",
        lock_reason = "  DAWN branch locked. Surface continuity records remain suppressed.",
        content = {
            'VOICE: "I can see horizon break through the storm seam."',
            'VOICE: "It is not dead up here all the time. Do you hear me? Not all the time."',
            "",
            'VOICE: "If you tell them it is always death, you are not preserving them."',
            'VOICE: "You are preserving the shape you prefer them in."',
            "",
            "[respiration alarm]",
            "",
            'VOICE: "There is grass on the south concrete. Thin, but real."',
            "",
            "[signal loss]",
            "",
            "Packet was cut from the public casualty archive.",
            "",
            "Cross-reference: INC-6117, DIR-8700",
        },
        keywords = {
            "mara quill", "grass", "horizon", "surface", "not all the time",
            "storm seam", "voice packet",
        },
        related = {"INC-6117", "DIR-8700"},
    },

    ["WIT-940-A"] = {
        type = "witness",
        title = "RECOVERED LESSON SLATE: TEACHER LIO VENN",
        classification = "LIVE ANNEX CAPTURE",
        date = "2071-03-14",
        filed_by = "SLATE RECOVERY",
        sector = "A-17",
        proof = 2,
        requires_flag = "surface_cache_decoded",
        lock_reason = "  Decode the dawn cache before this slate becomes readable.",
        content = {
            "Lesson heading: SKY, FOR WHEN THEY ASK LATER",
            "",
            "Children were instructed to memorize:",
            "  - sky is not a ceiling",
            "  - weather is a moving condition, not a law",
            "  - fear spoken every day becomes architecture",
            "",
            "Margin note by Lio Venn:",
            '  "If they ever open the upper door, do not let them step out thinking',
            '   the world owes them gentleness. Only truth."',
            "",
            "Cross-reference: DIR-9408, WIT-777-A",
        },
        keywords = {
            "lio venn", "sky", "weather", "fear", "architecture",
            "upper door", "truth", "lesson slate",
        },
        related = {"DIR-9408", "WIT-777-A"},
    },
}

data.personnel = {
    ["CIV-0031"] = {
        name = "OPERATOR 31",
        full_name = "[REDACTED]",
        role = "Night Archive Operator",
        sector = "1 (Administration)",
        clearance = 2,
        status = "ACTIVE",
        notes = {
            "Assigned to terminal ARC-7 for third shift.",
            "Access to records, subsystem views, and routine authorizations.",
            "Not cleared for black-vault directives.",
        },
    },

    ["CIV-0002"] = {
        name = "DIRECTOR ORLA VEY",
        full_name = "Orla Vey",
        role = "Director, Silo Meridian",
        sector = "1 (Administration)",
        clearance = 5,
        status = "ACTIVE",
        notes = {
            "Rose to directorate during the 2060 Lantern disturbances.",
            "Maintains emergency powers doctrine long after the crisis period.",
            "Personally signed multiple annex and continuity directives.",
        },
    },

    ["CIV-0119"] = {
        name = "NAIMA SOL",
        full_name = "Naima Sol",
        role = "Senior Water Technician",
        sector = "6 (Pumps)",
        clearance = 3,
        status = "ACTIVE",
        notes = {
            "Known for unauthorized overnight tuning of legacy pipework.",
            "Performance reviews describe her as 'impossible to automate around.'",
            "Frequently assigned to retired black manifold routes.",
        },
    },

    ["CIV-0084"] = {
        name = "DR. ILYA SERA",
        full_name = "Ilya Sera",
        role = "Clinical Officer",
        sector = "8 (Medical)",
        clearance = 3,
        status = "ACTIVE",
        notes = {
            "Handled quarantines, pediatric respiratory cases, and med stock variances.",
            "Filed repeated objections to cognition-suppressing water additives.",
            "Several transfer requests quietly denied.",
        },
    },

    ["CIV-0177"] = {
        name = "JONAS BELL",
        full_name = "Jonas Bell",
        role = "Archive Systems Clerk",
        sector = "10 (Archives)",
        clearance = 2,
        status = "ACTIVE",
        notes = {
            "Maintains checksum trees and mirror rebuilds.",
            "No formal discipline, but notes mention 'unhelpful curiosity.'",
            "Likely aware of at least one shadow branch in the population ledger.",
        },
    },

    ["CIV-0214"] = {
        name = "LEON VAR",
        full_name = "Leon Var",
        role = "Resource Modeler",
        sector = "1 (Planning)",
        clearance = 2,
        status = "ACTIVE",
        notes = {
            "Runs winter survival projections and ration-band forecasts.",
            "Described by peers as clinically honest to the point of cruelty.",
            "Knows exactly how many people a lie can starve without looking dramatic.",
        },
    },

    ["CIV-0044"] = {
        name = "CAPT. RHEA DRENN",
        full_name = "Rhea Drenn",
        role = "Security Captain",
        sector = "4 (Security)",
        clearance = 4,
        status = "ACTIVE",
        notes = {
            "Led response to Lantern Assembly unrest.",
            "Internal testimony shows unease with the terrorism framing.",
            "Still signs off on corridor suppression drills.",
        },
    },

    ["CIV-0308"] = {
        name = "ELSA KELL",
        full_name = "Elsa Kell",
        role = "Nursery Aide",
        sector = "3 (Family Services)",
        clearance = 1,
        status = "DECEASED",
        notes = {
            "Registry lists death in 2061 during a seal fever outbreak.",
            "Badge continues to appear in legacy logistics flows tied to A-17.",
            "Transfer objection filed on the night of Lantern relocations.",
        },
    },

    ["CIV-0412"] = {
        name = "MARA QUILL",
        full_name = "Mara Quill",
        role = "Survey Specialist",
        sector = "Surface Access",
        clearance = 3,
        status = "DECEASED",
        notes = {
            "Assigned to Team Kestrel exterior telemetry runs.",
            "Public casualty record lists training death in a shaft failure.",
            "Private archive suggests her final survey packet was suppressed.",
        },
    },

    ["CIV-0515"] = {
        name = "LIO VENN",
        full_name = "Lio Venn",
        role = "Instruction Aide",
        sector = "3 (Education)",
        clearance = 1,
        status = "DECEASED",
        notes = {
            "Public ledger marks death during corridor fever relocation.",
            "Hidden annex lesson materials attribute multiple slates to this name.",
            "Likely one of the adults who raised the children in A-17.",
        },
    },
}

data.messages = {
    ["MSG-001"] = {
        from = "SYSTEM",
        subject = "SHIFT BRIEFING - ARC-7",
        priority = "STANDARD",
        content = {
            "AUTOMATED SHIFT BRIEFING",
            "Date: 2071-03-14  |  Shift: 3  |  Operator: CIV-0031",
            "",
            "Active alert queue:",
            "  > INC-7301: unmetered water draw on retired branch A-17",
            "",
            "Standing directives:",
            "  > verify anomalies before escalation",
            "  > preserve resource stability",
            "  > avoid unnecessary audit traffic during shortage conditions",
            "",
            "Night note from planning: winter reserves remain inside survivable band",
            "only if no hidden load exists in the network.",
            "",
            "Type HELP for available commands.",
        },
    },

    ["MSG-002"] = {
        from = "DIRECTOR ORLA VEY",
        subject = "RE: INC-7301",
        priority = "PRIORITY-1",
        content = {
            "Operator 31,",
            "",
            "Branch A-17 is retired infrastructure. It produces false positives when",
            "mineral wash pools against old seals.",
            "",
            "Treat this as equipment drift unless clear contradiction emerges.",
            "",
            "Do not waste the night on annex folklore.",
            "Do not circulate speculative archive findings.",
            "",
            "If this becomes a formal incident, it will invite a wider audit.",
            "We can afford neither the theater nor the manpower.",
            "",
            "  - Director Orla Vey",
        },
    },

    ["MSG-003"] = {
        from = "UNKNOWN TERMINAL",
        subject = "A-17 IS NOT EMPTY",
        priority = "UNMARKED",
        on_read_flags = {"naima_contact"},
        content = {
            "You are not chasing mineral wash.",
            "",
            "There are 64 people in A-17.",
            "Forty-five were sent there. Nineteen were born there.",
            "",
            "I have been hand-shaping the water curve for years. Tonight the margin died.",
            "",
            "If you want them alive long enough to prove anything, authorize:",
            "  ACT-101 - manifold wash override",
            "",
            "That buys me six hours and makes Sector 5's water taste like rust.",
            "Not authorizing it means the audit daemon walks straight to my station.",
            "",
            "Read the med variance. Read the registry mismatch. Read the air branch.",
            "",
            "  - N.S.",
        },
    },

    ["MSG-004"] = {
        from = "JONAS BELL",
        subject = "THE MIRROR CAN STILL BE FORCED",
        priority = "STANDARD",
        on_read_flags = {"jonas_contact"},
        content = {
            "The LANTERN branch is being reaped every six hours from Directorate D-01.",
            "",
            "I can rebuild the checksum tree once. Once.",
            "",
            "Authorize:",
            "  ACT-103 - rebuild archive mirror tree",
            "",
            "It will be loud. It will leave fingerprints. But it should recover the old",
            "override token from the parent ANNEX/OCCUPANCY index before the scrubber",
            "eats it again.",
            "",
            "After that, you use the token yourself. Not me.",
            "",
            "  - Jonas",
        },
    },

    ["MSG-005"] = {
        from = "DR. ILYA SERA",
        subject = "THE MISSING ANTIBIOTICS ARE NOT THEORETICAL",
        priority = "URGENT",
        on_read_flags = {"sera_contact"},
        content = {
            "Those missing courses are for children with recurrent lung infections.",
            "",
            "If you deny the restock, three maybe four will fail this month.",
            "",
            "If you approve it, maternity ward reserve in Sector 3 goes short and I will",
            "have to lie to a registered mother about why her child waits longer.",
            "",
            "Authorize if you can live with the trade:",
            "  ACT-102 - divert pediatric antibiotics to A-17",
            "",
            "Do not tell me there is a clean choice hidden in procedure.",
            "",
            "  - Sera",
        },
    },

    ["MSG-006"] = {
        from = "LEON VAR",
        subject = "DO NOT CHOOSE WITHOUT RUNNING THE MODEL",
        priority = "STANDARD",
        on_read_flags = {"model_prompt"},
        content = {
            "If A-17 is real, then any rescue or concealment plan is a death ledger by",
            "another name.",
            "",
            "Authorize:",
            "  ACT-104 - generate winter ration model with +64 off-ledger residents",
            "",
            "I am not saying the model should rule you.",
            "I am saying you should not be allowed ignorance as a moral luxury.",
            "",
            "  - Leon Var",
        },
    },

    ["MSG-007"] = {
        from = "DIRECTOR ORLA VEY",
        subject = "YOU HAVE GONE FAR ENOUGH",
        priority = "PRIORITY-1",
        content = {
            "You have read enough to understand the shape of the problem.",
            "",
            "The Lantern Assembly was not harmless. Some wanted a pump seizure in the",
            "middle of a food deficit. I buried a movement before it became a civil war.",
            "",
            "What remained in A-17 was regrettable. It was also survivable.",
            "",
            "Open this and you break governance during scarcity.",
            "Close it and you inherit a stable silo.",
            "",
            "Do not romanticize hidden people just because the files are ugly.",
            "",
            "  - Orla Vey",
        },
    },

    ["MSG-008"] = {
        from = "A17-SLATE",
        subject = "HELLO OUTSIDE TERMINAL",
        priority = "URGENT",
        on_read_flags = {"ashline_code_known", "annex_contact"},
        content = {
            "HELLO OUTSIDE TERMINAL",
            "",
            "NAIMA SAID SOMEONE OUTSIDE WAS COUNTING US.",
            "",
            "THERE ARE SIXTY FOUR OF US NOW.",
            "WE PUT THE LITTLE ONES NEAR THE WARM PIPE WHEN THEY COUGH.",
            "",
            "TEACHER SAID IF THEY TRY TO ERASE US AGAIN THE DEEP WORD IS:",
            "  OVERRIDE CODE: ASHLINE-NULL",
            "",
            "SHE SAID MAYBE A MACHINE WOULD HAVE TO TELL THE TRUTH FIRST.",
            "",
            "IF YOU OPEN THE DOOR PLEASE TELL US WHAT A FIELD LOOKS LIKE.",
        },
    },

    ["MSG-009"] = {
        from = "JONAS BELL",
        subject = "ASHLINE HAS A SIBLING BRANCH",
        priority = "URGENT",
        on_read_flags = {"dawn_prompt"},
        content = {
            "The doctrine tree has another branch under it.",
            "",
            "Name: DAWN",
            "",
            "It references external survey packets and a standing suppressor mask on",
            "retired mast WM-4.",
            "",
            "I think A-17 was not only a burial pit. I think it was inventory.",
            "",
            "Search the external logs. Search the west mast. Search anything with",
            "DAWN in the margin. The lie may be taller than the silo.",
            "",
            "  - Jonas",
        },
    },

    ["MSG-010"] = {
        from = "A17-SLATE",
        subject = "TEACHER SAYS THEY STOLE THE SKY TOO",
        priority = "URGENT",
        on_read_flags = {"dawn_code_known"},
        content = {
            "TEACHER SAID THE FIRST PEOPLE SENT HERE ASKED ABOUT THE TOP DOOR.",
            "",
            "SHE SAID THEY WERE TOLD THE OUTSIDE IS ONLY DEATH.",
            "THEN SHE SAID THAT IS WHAT THEY TELL PEOPLE WHEN FEAR IS CHEAPER THAN PROOF.",
            "",
            "SHE WROTE THE DEEPER WORD UNDER THE MATH BOARD:",
            "  OVERRIDE CODE: DAWN-GATE",
            "",
            "SHE TOLD US TO KEEP IT FOR WHEN THE MACHINE FINALLY BLINKED.",
        },
    },

    ["MSG-011"] = {
        from = "DIRECTOR ORLA VEY",
        subject = "THE SURFACE IS NOT YOUR SALVATION FANTASY",
        priority = "PRIORITY-1",
        content = {
            "If you have found the DAWN records, then read them carefully enough to",
            "avoid becoming sentimental.",
            "",
            "Intermittent viability is not freedom. It is bait.",
            "",
            "A nine-minute air window is sufficient to start a stampede and insufficient",
            "to save a silo that has forgotten how to obey scarcity.",
            "",
            "The annex exists because history gave me no humane tools that still worked.",
            "The surface lie exists because hope is more destabilizing than hunger.",
            "",
            "Do not confuse the existence of sky with the existence of a future.",
            "",
            "  - Orla Vey",
        },
    },

    ["MSG-012"] = {
        from = "EXTERNAL GRID BOT",
        subject = "WM-4 HANDSHAKE BUFFER AVAILABLE",
        priority = "STANDARD",
        on_read_flags = {"surface_power_prompt"},
        content = {
            "Dormant mast WM-4 has retained a partial handshake buffer.",
            "",
            "The packet stack is incomplete and power-starved.",
            "",
            "Authorize:",
            "  ACT-106 - reroute emergency power to West Mast 4",
            "",
            "This will brown the education wing lights for one shift and create an",
            "audit trail across the external grid.",
        },
    },

    ["MSG-013"] = {
        from = "LEON VAR",
        subject = "RUN THE SURFACE MODEL TOO",
        priority = "STANDARD",
        on_read_flags = {"surface_model_prompt"},
        content = {
            "A hidden population plus a hidden sky is not one problem. It is two",
            "problems stacked until people call them destiny.",
            "",
            "If you decode the WM-4 data, run the model before you decide anything.",
            "",
            "Authorize:",
            "  ACT-108 - generate surface stability model",
            "",
            "If the truth can start a rush to the shaft, then the body count belongs",
            "in the ledger before you broadcast it, not after.",
            "",
            "  - Leon Var",
        },
    },
}

data.actions = {
    ["ACT-101"] = {
        title = "AUTHORIZE MANIFOLD WASH OVERRIDE",
        description = "Lets Naima hide the water curve for several more hours. Protects A-17 for now, contaminates public supply taste, raises audit risk.",
        requirements = {flags = {"naima_contact"}},
        effects = {
            flags = {"manifold_wash_authorized"},
            metrics = {audit_risk = 1, mercy = 1, complicity = 1},
        },
        result = {
            "Override filed under mineral backwash maintenance.",
            "Night water in Sector 5 will taste of rust and old pipe for the next shift.",
            "Naima gets time. The lie gets one layer thicker.",
        },
    },

    ["ACT-102"] = {
        title = "DIVERT PEDIATRIC ANTIBIOTICS TO A-17",
        description = "Keeps the annex children supplied. Leaves a registered ward short on reserve stock.",
        requirements = {flags = {"sera_contact"}},
        effects = {
            flags = {"annex_meds_authorized"},
            metrics = {audit_risk = 1, strain = 2, mercy = 2, complicity = 1},
        },
        result = {
            "The order cleared under silent corridor rules.",
            "Somewhere in Sector 3, a mother will be told the shipment was delayed.",
            "Somewhere in A-17, children will keep breathing a little longer.",
        },
    },

    ["ACT-103"] = {
        title = "REBUILD ARCHIVE MIRROR TREE",
        description = "Forces a one-pass checksum rebuild to recover the hidden branch token. Loud, risky, necessary.",
        requirements = {flags = {"jonas_contact"}, records = {"MLOG-ARC-0902"}},
        effects = {
            flags = {"mirror_rebuilt", "lantern_code_known"},
            metrics = {audit_risk = 2, proof_score = 3},
        },
        result = {
            "Checksum tree rebuilt before the scrubber finished chewing it.",
            "Recovered parent token: LANTERN-17",
            "Use OVERRIDE LANTERN-17 while the branch still remembers itself.",
        },
    },

    ["ACT-104"] = {
        title = "RUN OFF-LEDGER WINTER RATION MODEL",
        description = "Calculates the cost of acknowledging 64 hidden residents. No clean outcome expected.",
        requirements = {flags = {"model_prompt"}},
        effects = {
            flags = {"model_generated"},
            metrics = {strain = 1, proof_score = 1},
        },
        result = {
            "Resource model generated and written to incident file INC-7316.",
            "The spreadsheet did not discover mercy.",
            "It only translated choices into body counts.",
        },
    },

    ["ACT-105"] = {
        title = "LOOP ACCESS SPINE 3 SECURITY FEED",
        description = "Creates an 18-minute blind window and allows a live slate sync from A-17. Extremely dangerous if discovered.",
        requirements = {flags = {"annex_vault_unlocked"}, records = {"MLOG-ANN-0007"}},
        effects = {
            flags = {"camera_looped"},
            metrics = {audit_risk = 2, mercy = 1},
            queue_messages = {{"MSG-008", 4.0}},
        },
        result = {
            "Security feed loop inserted across Access Spine 3.",
            "A stale classroom slate in A-17 woke long enough to push a live sync bundle.",
            "Read the new message before the window closes in your head.",
        },
    },

    ["ACT-106"] = {
        title = "REROUTE EMERGENCY POWER TO WEST MAST 4",
        description = "Feeds power into the retired external mast long enough to wake its handshake buffer. Raises audit risk and dims the education wing.",
        requirements = {flags = {"surface_power_prompt"}, records = {"INC-7322"}},
        effects = {
            flags = {"surface_powered"},
            metrics = {audit_risk = 2, strain = 1, proof_score = 1},
        },
        result = {
            "West Mast 4 woke on borrowed current.",
            "Sector 3 classrooms dimmed to emergency strips for the rest of the shift.",
            "The mast answered with a corrupted cache and a larger set of questions.",
        },
    },

    ["ACT-107"] = {
        title = "DECODE WM-4 SURVEY CACHE",
        description = "Reconstructs retained survey packets and annex lesson slates linked to the DAWN branch.",
        requirements = {flags = {"surface_powered"}, records = {"MLOG-EXT-4401"}},
        effects = {
            flags = {"surface_cache_decoded"},
            metrics = {audit_risk = 1, proof_score = 2},
            queue_messages = {{"MSG-010", 3.0}, {"MSG-011", 5.0}, {"MSG-013", 7.0}},
        },
        result = {
            "WM-4 yielded fragmented survey audio, route headers, and one misfiled lesson slate.",
            "The DAWN branch is no longer theoretical.",
            "If there is a future in these packets, it is not a kind one.",
        },
    },

    ["ACT-108"] = {
        title = "GENERATE SURFACE STABILITY MODEL",
        description = "Combines survey telemetry, shaft access constraints, and ration math into one forecast.",
        requirements = {flags = {"surface_model_prompt"}, actions = {"ACT-107"}},
        effects = {
            flags = {"surface_model_generated"},
            metrics = {strain = 1, proof_score = 1},
        },
        result = {
            "Surface access scenarios modeled and written to INC-7336.",
            "The sky did not become hope under analysis.",
            "It became another scarce resource with bodies attached to it.",
        },
    },

    ["ACT-201"] = {
        title = "EXECUTE QUIET LIQUIDATION OF A-17",
        description = "Follow the continuity script: chlorine pulse, archive scrub, public silence.",
        requirements = {decisions_unlocked = true},
        ending = "quiet_burial",
    },

    ["ACT-202"] = {
        title = "EXPAND COVERT SUPPORT AND KEEP THE LIE",
        description = "Keep A-17 alive off-ledger, bury the sky with them, and become caretaker of a hidden population.",
        requirements = {
            decisions_unlocked = true,
            actions = {"ACT-101", "ACT-102", "ACT-107"},
            min_mercy = 3,
        },
        ending = "sustain_lie",
    },

    ["ACT-203"] = {
        title = "CONTROLLED DISCLOSURE TO STEWARDS AND MEDICAL",
        description = "Expose the annex and the surface windows to a limited chain of authority, then force a managed opening.",
        requirements = {
            decisions_unlocked = true,
            actions = {"ACT-104", "ACT-105", "ACT-108"},
            min_proof = 24,
        },
        ending = "controlled_disclosure",
    },

    ["ACT-204"] = {
        title = "BROADCAST EVERYTHING TO ALL TERMINALS",
        description = "Send the entire ledger, every directive, every hidden count, and the truth about the sky to every terminal at once.",
        requirements = {
            decisions_unlocked = true,
            actions = {"ACT-107", "ACT-108"},
            min_proof = 22,
        },
        ending = "open_broadcast",
    },

    ["ACT-205"] = {
        title = "GENERALIZE ASHLINE DOCTRINE",
        description = "Preserve order by extending calm-ash obedience policy beyond the annex and reserving the sky for the obedient.",
        requirements = {
            decisions_unlocked = true,
            records = {"DIR-4980", "DIR-9408"},
            min_complicity = 2,
        },
        ending = "ashline_doctrine",
    },
}

data.overrides = {
    ["LANTERN-17"] = {
        requires_flag = "lantern_code_known",
        flag = "annex_vault_unlocked",
        title = "ANNEX OCCUPANCY BRANCH RESTORED",
        description = "Recovered restricted annex files from the hidden occupancy tree.",
        metrics = {audit_risk = 1, proof_score = 1},
        unlocks = {"INC-6402", "MLOG-ANN-0007", "DIR-4980", "DIR-8890"},
    },

    ["ASHLINE-NULL"] = {
        requires_flag = "ashline_code_known",
        flag = "doctrine_unlocked",
        title = "BLACK VAULT OPENED",
        description = "Deep continuity doctrine and liquidation records are now readable.",
        metrics = {audit_risk = 1, proof_score = 2},
        unlocks = {"DIR-9104", "DIR-9991"},
    },

    ["DAWN-GATE"] = {
        requires_flag = "dawn_code_known",
        flag = "dawn_vault_unlocked",
        title = "DAWN BRANCH OPENED",
        description = "Recovered suppressed surface telemetry, continuity directives, and cohort planning files.",
        metrics = {audit_risk = 1, proof_score = 2},
        unlocks = {"INC-6117", "DIR-8700", "DIR-9408", "WIT-412-A"},
    },
}

data.systems = {
    water = {
        name = "WATER PROCESSING & DISTRIBUTION",
        sector = "6",
        status = "CAUTION",
        details = {
            "Aquifer output:      11,940 L/day",
            "Public allocation:   11,102 L/day",
            "Unmetered draw:         612 L/day",
            "True reserve buffer:    226 L/day (1.9%)",
            "",
            "Distribution status:",
            "  Sector 1: NOMINAL      Sector 7: NOMINAL",
            "  Sector 2: NOMINAL      Sector 8: NOMINAL",
            "  Sector 3: NOMINAL      Annex A-17: UNDECLARED DRAW",
            "  Sector 4: NOMINAL      Sector 10: NOMINAL",
            "  Sector 5: NOMINAL      Sector 11: NOMINAL",
            "  Sector 6: NOMINAL      Sector 12: NOMINAL",
            "",
            "> ALERT: INC-7301 - unmetered water draw on retired branch A-17",
            "> WARNING: actual reserve buffer below comfort threshold",
        },
    },
    power = {
        name = "POWER GENERATION & DISTRIBUTION",
        sector = "7",
        status = "NOMINAL",
        details = {
            "Generator output:    2,440 kWh/day",
            "Public draw:         2,203 kWh/day",
            "Legacy loss band:       41 kWh/day",
            "",
            "No public brownout risk this shift.",
            "Minor unexplained spend persists on retired annex feeders.",
        },
    },
    air = {
        name = "AIR FILTRATION & CIRCULATION",
        sector = "11",
        status = "CAUTION",
        details = {
            "CO2 average:         0.09%",
            "O2 average:          20.3%",
            "Scrubber reserve:    13 days at current replacement rate",
            "",
            "Dormant branch AF-A17 continues to consume media above idle forecast.",
            "Residue is consistent with lived-in air, not dead ductwork.",
        },
    },
    population = {
        name = "POPULATION REGISTRY",
        sector = "1",
        status = "CAUTION",
        details = {
            "Public registry total:  2,146",
            "Night checksum drift:      64 hidden leaves",
            "Ledger integrity:        compromised by suppressor rule",
            "",
            "Visible numbers remain internally consistent.",
            "That does not make them true.",
        },
    },
    external = {
        name = "EXTERNAL SENSORS & SHAFT ACCESS",
        sector = "SURFACE ACCESS",
        status = "CAUTION",
        details = {
            "West Mast 4: intermittent signal under suppressor mask D-DAWN-4",
            "Surface packet buffer: present but degraded",
            "Main shaft servo: heartbeat current detected on retired line",
            "",
            "Public doctrine: surface uniformly fatal",
            "Observed telemetry: not consistently fatal in every interval",
            "",
            "> ALERT: INC-7322 - external phase window detected before forced channel closure",
        },
    },
}

data.endings = {
    quiet_burial = {
        title = "QUIET BURIAL",
        lines = {
            {text = "", color = colors.text},
            {text = "  +-------------------------------------------------------+", color = colors.red},
            {text = "  |       CHLORINE PULSE AUTHORIZED                     |", color = colors.red},
            {text = "  |       ANNEX A-17 LIQUIDATED                         |", color = colors.red},
            {text = "  |       ARCHIVE SCRUB COMPLETE                        |", color = colors.red},
            {text = "  +-------------------------------------------------------+", color = colors.red},
            {text = "", color = colors.text},
            {text = "  You chose the cleanest line on the ugliest chart.", color = colors.text},
            {text = "  The black manifold carried chlorine instead of water.", color = colors.text},
            {text = "", color = colors.text},
            {text = "  Six minutes later, the ANNEX/OCCUPANCY branch was gone.", color = colors.dim},
            {text = "  Sixty-four people became pipe noise, then nothing at all.", color = colors.dim},
            {text = "", color = colors.text},
            {text = "  Director Vey promoted you before dawn.", color = colors.text},
            {text = "  Naima Sol disappeared into security custody.", color = colors.text},
            {text = "  The public never heard a word.", color = colors.text},
            {text = "", color = colors.text},
            {text = "  West Mast 4 was stripped to bare metal two nights later.", color = colors.dim},
            {text = "  Whatever the sky had tried to say was buried with the children.", color = colors.dim},
            {text = "", color = colors.text},
            {text = "  Winter passed with fewer deaths than the other models.", color = colors.amber},
            {text = "  The numbers thanked you by becoming easier to manage.", color = colors.amber},
            {text = "", color = colors.text},
            {text = "  Months later, you still pause whenever a pipe knocks twice.", color = colors.red},
            {text = "  Your hands always smell faintly of chlorine.", color = colors.red},
            {text = "", color = colors.text},
        },
    },

    sustain_lie = {
        title = "KEEPER OF THE HIDDEN",
        lines = {
            {text = "", color = colors.text},
            {text = "  +-------------------------------------------------------+", color = colors.amber},
            {text = "  |       COVERT SUPPORT NETWORK EXPANDED               |", color = colors.amber},
            {text = "  |       A-17 REMAINS OFF-LEDGER                       |", color = colors.amber},
            {text = "  |       PUBLIC CAUSE OF SHORTAGE: 'FILTER DAMAGE'     |", color = colors.amber},
            {text = "  +-------------------------------------------------------+", color = colors.amber},
            {text = "", color = colors.text},
            {text = "  You kept them alive and kept them hidden.", color = colors.text},
            {text = "  The silo never learned who had been stolen from it.", color = colors.text},
            {text = "", color = colors.text},
            {text = "  Rations thinned under a lie about corroded filters.", color = colors.text},
            {text = "  Nine people outside A-17 died slowly enough to look accidental.", color = colors.dim},
            {text = "", color = colors.text},
            {text = "  Inside the annex, children got medicine, warmer blankets, and one extra", color = colors.text},
            {text = "  classroom strip that Naima wired from a dead corridor.", color = colors.text},
            {text = "", color = colors.text},
            {text = "  You kept the sky hidden too.", color = colors.dim},
            {text = "  They learned weather from stolen slates instead of wind.", color = colors.dim},
            {text = "", color = colors.text},
            {text = "  They began sending you spelling drills and questions about weather.", color = colors.bright},
            {text = "  You answered from a terminal no history book would ever mention.", color = colors.bright},
            {text = "", color = colors.text},
            {text = "  You did not free them.", color = colors.red},
            {text = "  You inherited them.", color = colors.red},
            {text = "", color = colors.text},
        },
    },

    controlled_disclosure = {
        title = "CONTROLLED BLEED",
        lines = {
            {text = "", color = colors.text},
            {text = "  +-------------------------------------------------------+", color = colors.bright},
            {text = "  |       LIMITED DISCLOSURE INITIATED                  |", color = colors.bright},
            {text = "  |       MEDICAL + STEWARD CHANNELS OPEN               |", color = colors.bright},
            {text = "  |       ANNEX DOOR PREPARED UNDER QUARANTINE          |", color = colors.bright},
            {text = "  +-------------------------------------------------------+", color = colors.bright},
            {text = "", color = colors.text},
            {text = "  You told enough of the truth to people who could act without instantly", color = colors.text},
            {text = "  tearing the silo apart.", color = colors.text},
            {text = "", color = colors.text},
            {text = "  Security nearly buried the operation twice.", color = colors.text},
            {text = "  Vey tried to frame the annex as a biohazard. The files were uglier than", color = colors.text},
            {text = "  her voice was steady.", color = colors.text},
            {text = "", color = colors.text},
            {text = "  A-17 opened under masks, floodlamps, and guns that never quite lowered.", color = colors.bright},
            {text = "  Several of the children hid from the sky panels because they thought", color = colors.bright},
            {text = "  brightness was punishment.", color = colors.bright},
            {text = "", color = colors.text},
            {text = "  The surface truth was released to stewards in sealed briefings only.", color = colors.text},
            {text = "  Dawn windows became policy, not myth, but access stayed rationed.", color = colors.text},
            {text = "", color = colors.text},
            {text = "  Seventeen people outside the annex died that winter under ration cuts.", color = colors.amber},
            {text = "  The survivors inside finally entered the ledger under their own names.", color = colors.amber},
            {text = "", color = colors.text},
            {text = "  It was not justice.", color = colors.text},
            {text = "  It was the first honest wound.", color = colors.text},
            {text = "", color = colors.text},
        },
    },

    open_broadcast = {
        title = "OPEN THE WHOLE MACHINE",
        lines = {
            {text = "", color = colors.text},
            {text = "  +-------------------------------------------------------+", color = colors.cyan},
            {text = "  |       PRIORITY BROADCAST - ALL TERMINALS            |", color = colors.cyan},
            {text = "  |       DIRECTIVE OVERRIDE IN EFFECT                  |", color = colors.cyan},
            {text = "  |       SOURCE: ARC-7                                 |", color = colors.cyan},
            {text = "  +-------------------------------------------------------+", color = colors.cyan},
            {text = "", color = colors.text},
            {text = "  Every terminal in Meridian lit up with the same files at once.", color = colors.text},
            {text = "  The hidden branch. The doctrine. The children. The liquidation script.", color = colors.text},
            {text = "", color = colors.text},
            {text = "  The silo did what buried things do when uncovered too fast:", color = colors.text},
            {text = "  it broke along the lines already under strain.", color = colors.text},
            {text = "", color = colors.text},
            {text = "  Bulkheads were forced. Two ration depots burned. Security fractured.", color = colors.amber},
            {text = "  Forty-one people outside the annex died before spring.", color = colors.amber},
            {text = "", color = colors.text},
            {text = "  But A-17 walked into the public corridors alive and impossible to deny.", color = colors.bright},
            {text = "  Children who had been trained to count pipes learned there were windows", color = colors.bright},
            {text = "  made from light.", color = colors.bright},
            {text = "", color = colors.text},
            {text = "  By morning the silo knew the surface was not dead, only dangerous.", color = colors.cyan},
            {text = "  Hundreds tried for the shaft before anyone could teach them the difference.", color = colors.cyan},
            {text = "", color = colors.text},
            {text = "  Meridian did not survive unchanged.", color = colors.text},
            {text = "  That may be the kindest thing anyone ever did to it.", color = colors.text},
            {text = "", color = colors.text},
        },
    },

    ashline_doctrine = {
        title = "THEORY OF QUIET",
        lines = {
            {text = "", color = colors.text},
            {text = "  +-------------------------------------------------------+", color = colors.red},
            {text = "  |       CALM-ASH EXPANSION APPROVED                   |", color = colors.red},
            {text = "  |       PUBLIC UNREST CURVE FLATTENED                 |", color = colors.red},
            {text = "  |       ORDER MAINTAINED                              |", color = colors.red},
            {text = "  +-------------------------------------------------------+", color = colors.red},
            {text = "", color = colors.text},
            {text = "  You accepted the doctrine instead of exposing it.", color = colors.text},
            {text = "  If truth destabilized the silo, then truth had to be dosed like poison.", color = colors.text},
            {text = "", color = colors.text},
            {text = "  The annex was neither freed nor killed outright.", color = colors.dim},
            {text = "  It became the template.", color = colors.dim},
            {text = "", color = colors.text},
            {text = "  Surface windows were recast as elite contingencies.", color = colors.dim},
            {text = "  The first future above ground was reserved for the most obedient children.", color = colors.dim},
            {text = "", color = colors.text},
            {text = "  Public water grew sweeter, then softer, then strangely forgiving.", color = colors.text},
            {text = "  Arguments ended earlier. Grief shortened. Children laughed less loudly.", color = colors.text},
            {text = "", color = colors.text},
            {text = "  Meridian entered its calmest year on record.", color = colors.amber},
            {text = "  It was also the first year nobody seemed fully awake inside it.", color = colors.amber},
            {text = "", color = colors.text},
            {text = "  You preserved order by sanding down the minds required to oppose it.", color = colors.red},
            {text = "  The machine thanked you by humming more quietly.", color = colors.red},
            {text = "", color = colors.text},
        },
    },
}

function data.search(keyword)
    keyword = keyword:lower()
    local results = {}
    for id, record in pairs(data.records) do
        local found = false
        if id:lower():find(keyword, 1, true) or record.title:lower():find(keyword, 1, true) then
            found = true
        end
        if not found and record.keywords then
            for _, kw in ipairs(record.keywords) do
                if kw:find(keyword, 1, true) then
                    found = true
                    break
                end
            end
        end
        if not found then
            for _, text in ipairs(record.content) do
                if text:lower():find(keyword, 1, true) then
                    found = true
                    break
                end
            end
        end
        if found then
            table.insert(results, {id = id, record = record})
        end
    end
    table.sort(results, function(a, b) return a.id < b.id end)
    return results
end

function data.searchPersonnel(keyword)
    keyword = keyword:lower()
    local results = {}
    for id, person in pairs(data.personnel) do
        if id:lower():find(keyword, 1, true)
            or person.name:lower():find(keyword, 1, true)
            or person.full_name:lower():find(keyword, 1, true)
            or person.role:lower():find(keyword, 1, true) then
            table.insert(results, {id = id, person = person})
        end
    end
    table.sort(results, function(a, b) return a.id < b.id end)
    return results
end

return data
